PipeWire: pw_pipewire Class Reference
pw_pipewire Class Reference
PipeWire initalization and infrasctructure functions.
Public Member Functions
SPA_EXPORT void pw_init (int *argc, char **argv[])
Initialize PipeWire.
SPA_EXPORT bool pw_debug_is_category_enabled (const char *name)
Check if a debug category is enabled.
SPA_EXPORT const char * pw_get_application_name (void)
Get the application name.
SPA_EXPORT const char * pw_get_prgname (void)
Get the program name.
SPA_EXPORT const char * pw_get_user_name (void)
Get the user name.
SPA_EXPORT const char * pw_get_host_name (void)
Get the host name.
SPA_EXPORT const char * pw_get_client_name (void)
Get the client name.
SPA_EXPORT void pw_fill_remote_properties (struct pw_core *core, struct pw_properties *properties)
Fill remote properties.
SPA_EXPORT void pw_fill_stream_properties (struct pw_core *core, struct pw_properties *properties)
Fill stream properties.
SPA_EXPORT enum pw_direction pw_direction_reverse (enum pw_direction direction)
Reverse the direction.
Detailed Description
PipeWire initalization and infrasctructure functions.
Member Function Documentation
pw_debug_is_category_enabled()
SPA_EXPORT bool pw_debug_is_category_enabled (const char * name)
Check if a debug category is enabled.
Parameters
name the name of the category to check
Returns
true if enabled
Debugging categories can be enabled by using the PIPEWIRE_DEBUG environment variable
pw_direction_reverse()
SPA_EXPORT enum pw_direction pw_direction_reverse (enum pw_direction direction)
Reverse the direction.
References PW_DIRECTION_INPUT, and PW_DIRECTION_OUTPUT.
Referenced by pw_core::pw_core_find_port(), pw_port_init_mix(), and pw_port_set_param().
pw_fill_remote_properties()
SPA_EXPORT void pw_fill_remote_properties (struct pw_core * core, struct pw_properties * properties)
Fill remote properties.
Parameters
properties a pw_properties
Fill properties with a set of default remote properties.
References pw_get_client_name(), pw_get_host_name(), pw_get_prgname(), pw_get_user_name(), PW_KEY_APP_LANGUAGE, PW_KEY_APP_NAME, PW_KEY_APP_PROCESS_BINARY, PW_KEY_APP_PROCESS_HOST, PW_KEY_APP_PROCESS_ID, PW_KEY_APP_PROCESS_SESSION_ID, PW_KEY_APP_PROCESS_USER, PW_KEY_CORE_DAEMON, PW_KEY_CORE_NAME, PW_KEY_CORE_VERSION, PW_KEY_WINDOW_X11_DISPLAY, pw_properties::pw_properties_get(), pw_properties::pw_properties_set(), and pw_properties::pw_properties_setf().
Referenced by pw_remote_new().
pw_fill_stream_properties()
SPA_EXPORT void pw_fill_stream_properties (struct pw_core * core, struct pw_properties * properties)
Fill stream properties.
Parameters
properties a pw_properties
Fill properties with a set of default stream properties.
pw_get_application_name()
SPA_EXPORT const char * pw_get_application_name (void)
Get the application name.
Referenced by pw_get_client_name().
pw_get_client_name()
SPA_EXPORT const char * pw_get_client_name (void)
Get the client name.
Make a new PipeWire client name that can be used to construct a remote.
References pw_get_application_name(), and pw_get_prgname().
Referenced by pw_fill_remote_properties().
pw_get_host_name()
SPA_EXPORT const char * pw_get_host_name (void)
Get the host name.
Referenced by pw_core::pw_core_new(), and pw_fill_remote_properties().
pw_get_prgname()
SPA_EXPORT const char * pw_get_prgname (void)
Get the program name.
Referenced by pw_fill_remote_properties(), and pw_get_client_name().
pw_get_user_name()
SPA_EXPORT const char * pw_get_user_name (void)
Get the user name.
Referenced by pw_core::pw_core_new(), and pw_fill_remote_properties().
pw_init()
SPA_EXPORT void pw_init (int * argc, char ** argv[])
Initialize PipeWire.
Parameters
argc pointer to argc
argv pointer to argv
Initialize the PipeWire system, parse and modify any parameters given by argc and argv and set up debugging.
The environment variable PIPEWIRE_DEBUG
The documentation for this class was generated from the following files:
pipewire.h
pipewire.c