PipeWire: pw_node Class Reference
pw_node Class Reference
PipeWire node class.
Public Member Functions
const char * pw_node_state_as_string (enum pw_node_state state)
Convert a pw_node_state to a readable string.
struct pw_node * pw_node_new (struct pw_core *core, const char *name, struct pw_properties *properties, size_t user_data_size)
Create a new node.
SPA_EXPORT void pw_node_destroy (struct pw_node *node)
Destroy a node.
SPA_EXPORT int pw_node_set_state (struct pw_node *node, enum pw_node_state state)
Set the node state.
Detailed Description
PipeWire node class.
Member Function Documentation
pw_node_destroy()
SPA_EXPORT void pw_node_destroy (struct pw_node * node)
Destroy a node.
Parameters
node a node to destroy
Remove node. This will stop the transfer on the node and free the resources allocated by node.
References pw_log::pw_log_debug.
Referenced by pw_core::pw_core_destroy(), pw_device_destroy(), and pw_stream_disconnect().
pw_node_new()
struct pw_node * pw_node_new (struct pw_core * core, const char * name, struct pw_properties * properties, size_t user_data_size)
Create a new node.
Parameters
core the core
name node name
properties extra properties
user_data_size user data size
pw_node_set_state()
SPA_EXPORT int pw_node_set_state (struct pw_node * node, enum pw_node_state state)
Set the node state.
Parameters
node a pw_node
state a pw_node_state
Returns
0 on success < 0 on error
Set the state of node to state.
References pw_log::pw_log_debug, pw_node_state_as_string(), PW_NODE_STATE_CREATING, and PW_NODE_STATE_SUSPENDED.
Referenced by pw_node_set_active().
pw_node_state_as_string()
const char * pw_node_state_as_string (enum pw_node_state state)
Convert a pw_node_state to a readable string.
Referenced by pw_node_set_state().
The documentation for this class was generated from the following files:
node.h
introspect.h
node.c