PipeWire: pw_core Class Reference
pw_core Class Reference
the core PipeWire object
Public Member Functions
SPA_EXPORT struct pw_core * pw_core_new (struct pw_loop *main_loop, struct pw_properties *properties, size_t user_data_size)
Create a new core object.
SPA_EXPORT void pw_core_destroy (struct pw_core *core)
Destroy a core object.
SPA_EXPORT int pw_core_update_properties (struct pw_core *core, const struct spa_dict *dict)
Update core properties.
struct pw_port * pw_core_find_port (struct pw_core *core, struct pw_port *other_port, uint32_t id, struct pw_properties *props, uint32_t n_format_filters, struct spa_pod **format_filters, char **error)
Find a port to link with.
int pw_core_find_format (struct pw_core *core, struct pw_port *output, struct pw_port *input, struct pw_properties *props, uint32_t n_format_filters, struct spa_pod **format_filters, struct spa_pod **format, struct spa_pod_builder *builder, char **error)
Find a common format between two ports.
SPA_EXPORT struct pw_factory * pw_core_find_factory (struct pw_core *core, const char *name)
Find a factory by name.
Detailed Description
the core PipeWire object
The core object manages all available resources.
See Core API
Member Function Documentation
pw_core_destroy()
SPA_EXPORT void pw_core_destroy (struct pw_core * core)
Destroy a core object.
Parameters
core a core to destroy
References pw_array_for_each, pw_data_loop::pw_data_loop_destroy(), pw_device_destroy(), pw_global::pw_global_destroy(), pw_log::pw_log_debug, pw_mempool_destroy(), pw_module::pw_module_destroy(), pw_node::pw_node_destroy(), pw_properties::pw_properties_free(), pw_remote::pw_remote_destroy(), pw_resource_destroy(), and pw_unload_spa_handle().
Referenced by pw_stream_new_simple().
pw_core_find_factory()
SPA_EXPORT struct pw_factory * pw_core_find_factory (struct pw_core * core, const char * name)
Find a factory by name.
Parameters
core the core object
name the name of the factory to find
Find in the list of factories registered in core for one with the given name.
pw_core_find_format()
int pw_core_find_format (struct pw_core * core, struct pw_port * output, struct pw_port * input, struct pw_properties * props, uint32_t n_format_filters, struct spa_pod ** format_filters, struct spa_pod ** format, struct spa_pod_builder * builder, char ** error)
Find a common format between two ports.
Parameters
core a core object
output an output port
input an input port
props extra properties
n_format_filters number of format filters
format_filters array of format filters
[out] error an error when something is wrong
Returns
a common format of NULL on error
Find a common format between the given ports. The format will be restricted to a subset given with the format filters.
References pw_log::pw_log_debug, pw_log::pw_log_level_enabled, PW_NODE_STATE_IDLE, and PW_PORT_STATE_CONFIGURE.
Referenced by pw_core_find_port().
pw_core_find_port()
struct pw_port * pw_core_find_port (struct pw_core * core, struct pw_port * other_port, uint32_t id, struct pw_properties * props, uint32_t n_format_filters, struct spa_pod ** format_filters, char ** error)
Find a port to link with.
Parameters
core a core
other_port a port to find a link with
id the id of a port or SPA_ID_INVALID
props extra properties
n_format_filters number of filters
format_filters array of format filters
[out] error an error when something is wrong
Returns
a port that can be used to link to otherport or NULL on error
References pw_core_find_format(), PW_DIRECTION_OUTPUT, pw_pipewire::pw_direction_reverse(), pw_global_get_permissions(), pw_log::pw_log_debug, pw_node_find_port(), and PW_PERM_IS_R.
pw_core_new()
SPA_EXPORT struct pw_core * pw_core_new (struct pw_loop * main_loop, struct pw_properties * properties, size_t user_data_size)
Create a new core object.
Parameters
main_loop the main loop to use
properties extra properties for the core, ownership it taken
Returns
a newly allocated core object
References pw_properties::dict, pw_loop::loop, pw_array::pw_array_init(), pw_data_loop_get_loop(), pw_data_loop::pw_data_loop_new(), pw_data_loop::pw_data_loop_start(), pw_pipewire::pw_get_host_name(), pw_get_library_version(), pw_get_support(), pw_pipewire::pw_get_user_name(), pw_global::pw_global_new(), PW_KEY_CORE_NAME, PW_KEY_CORE_VERSION, PW_KEY_HOST_NAME, PW_KEY_LIBRARY_NAME_DBUS, PW_KEY_LIBRARY_NAME_SYSTEM, PW_KEY_USER_NAME, pw_load_spa_handle(), pw_log::pw_log_debug, pw_log::pw_log_warn, pw_map::pw_map_init(), pw_mempool_new(), pw_properties::pw_properties_copy(), pw_properties::pw_properties_get(), pw_properties::pw_properties_new(), pw_properties::pw_properties_set(), pw_properties::pw_properties_setf(), PW_TYPE_INTERFACE_Core, PW_VERSION_CORE_PROXY, pw_loop::system, impl::this, and pw_loop::utils.
Referenced by pw_stream_new_simple().
pw_core_update_properties()
SPA_EXPORT int pw_core_update_properties (struct pw_core * core, const struct spa_dict * dict)
Update core properties.
Parameters
core a core
dict properties to update
Update the core object with the given properties
References PW_CORE_CHANGE_MASK_PROPS, pw_log::pw_log_debug, and pw_properties::pw_properties_update().
The documentation for this class was generated from the following files:
core.h
core.c