PipeWire: pw_stream Class Reference
pw_stream Class Reference
PipeWire stream object class.
Public Member Functions
const char * pw_stream_state_as_string (enum pw_stream_state state)
Convert a stream state to a readable string.
struct pw_stream * pw_stream_new (struct pw_remote *remote, const char *name, struct pw_properties *props)
Create a new unconneced pw_stream.
void pw_stream_destroy (struct pw_stream *stream)
Destroy a stream.
int pw_stream_connect (struct pw_stream *stream, enum pw_direction direction, uint32_t target_id, enum pw_stream_flags flags, const struct spa_pod **params, uint32_t n_params)
Connect a stream for input or output on port_path.
uint32_t pw_stream_get_node_id (struct pw_stream *stream)
Get the node ID of the stream.
int pw_stream_disconnect (struct pw_stream *stream)
Disconnect stream.
void pw_stream_finish_format (struct pw_stream *stream, int res, const struct spa_pod **params, uint32_t n_params)
Complete the negotiation process with result code res.
int pw_stream_get_time (struct pw_stream *stream, struct pw_time *time)
Query the time on the stream.
int pw_stream_set_active (struct pw_stream *stream, bool active)
Activate or deactivate the stream.
Detailed Description
PipeWire stream object class.
The stream object provides a convenient way to send and receive data streams from/to PipeWire.
See also Media Streams and Core API
Member Function Documentation
pw_stream_connect()
int pw_stream_connect (struct pw_stream * stream, enum pw_direction direction, uint32_t target_id, enum pw_stream_flags flags, const struct spa_pod ** params, uint32_t n_params)
Connect a stream for input or output on port_path.
Returns
0 on success < 0 on error.
You should connect to the process event and use pw_stream_dequeue_buffer() to get the latest metadata and data.
Parameters
stream a pw_stream
direction the stream direction
target_id the target node to connect to or SPA_ID_INVALID to let the manager select a node.
flags stream flags
params an array with params. The params should ideally contain supported formats.
n_params number of items in params
pw_stream_destroy()
void pw_stream_destroy (struct pw_stream * stream)
Destroy a stream.
Referenced by pw_remote_destroy().
pw_stream_disconnect()
int pw_stream_disconnect (struct pw_stream * stream)
Disconnect stream.
Referenced by pw_remote_disconnect(), and pw_stream_destroy().
pw_stream_finish_format()
void pw_stream_finish_format (struct pw_stream * stream, int res, const struct spa_pod ** params, uint32_t n_params)
Complete the negotiation process with result code res.
This function should be called after notification of the format.
When res indicates success, params contain the parameters for the allocation state.
Parameters
stream a pw_stream
res a result code
params an array of params. The params should ideally contain parameters for doing buffer allocation.
n_params number of elements in params
pw_stream_get_node_id()
uint32_t pw_stream_get_node_id (struct pw_stream * stream)
Get the node ID of the stream.
Returns
node ID.
pw_stream_get_time()
int pw_stream_get_time (struct pw_stream * stream, struct pw_time * time)
Query the time on the stream.
pw_stream_new()
struct pw_stream * pw_stream_new (struct pw_remote * remote, const char * name, struct pw_properties * props)
Create a new unconneced pw_stream.
Returns
a newly allocated pw_stream
Parameters
remote a pw_remote
name a stream name
props stream properties, ownership is taken
Referenced by pw_stream_new_simple().
pw_stream_set_active()
int pw_stream_set_active (struct pw_stream * stream, bool active)
Activate or deactivate the stream.
pw_stream_state_as_string()
const char * pw_stream_state_as_string (enum pw_stream_state state)
Convert a stream state to a readable string.
The documentation for this class was generated from the following file:
stream.h