PipeWire: client.h File Reference
client.h File Reference
Data Structures
struct pw_client_events
The events that a client can emit.
Macros
#define PW_VERSION_CLIENT_EVENTS 0
Functions
struct pw_client * pw_client_new (struct pw_core *core, struct pw_properties *properties, size_t user_data_size)
Create a new client.
void pw_client_destroy (struct pw_client *client)
Destroy a previously created client.
int pw_client_register (struct pw_client *client, struct pw_client *owner, struct pw_global *parent, struct pw_properties *properties)
Finish configuration and register a client.
void * pw_client_get_user_data (struct pw_client *client)
Get the client user data.
const struct pw_client_info * pw_client_get_info (struct pw_client *client)
Get the client information.
int pw_client_update_properties (struct pw_client *client, const struct spa_dict *dict)
Update the client properties.
int pw_client_update_permissions (struct pw_client *client, uint32_t n_permissions, const struct pw_permission *permissions)
Update the client permissions.
const struct pw_properties * pw_client_get_properties (struct pw_client *client)
Get the client properties.
struct pw_core * pw_client_get_core (struct pw_client *client)
Get the core used to create this client.
struct pw_resource * pw_client_get_core_resource (struct pw_client *client)
Get the client core resource.
struct pw_resource * pw_client_find_resource (struct pw_client *client, uint32_t id)
Get a resource with the given id.
struct pw_global * pw_client_get_global (struct pw_client *client)
Get the global associated with this client.
void pw_client_add_listener (struct pw_client *client, struct spa_hook *listener, const struct pw_client_events *events, void *data)
listen to events from this client
void pw_client_set_busy (struct pw_client *client, bool busy)
Mark the client busy.
Macro Definition Documentation
PW_VERSION_CLIENT_EVENTS
#define PW_VERSION_CLIENT_EVENTS 0
Function Documentation
pw_client_add_listener()
void pw_client_add_listener (struct pw_client * client, struct spa_hook * listener, const struct pw_client_events * events, void * data)
listen to events from this client
pw_client_destroy()
void pw_client_destroy (struct pw_client * client)
Destroy a previously created client.
pw_client_find_resource()
struct pw_resource* pw_client_find_resource (struct pw_client * client, uint32_t id)
Get a resource with the given id.
References pw_map::pw_map_lookup().
pw_client_get_core()
struct pw_core* pw_client_get_core (struct pw_client * client)
Get the core used to create this client.
pw_client_get_core_resource()
struct pw_resource* pw_client_get_core_resource (struct pw_client * client)
Get the client core resource.
pw_client_get_global()
struct pw_global* pw_client_get_global (struct pw_client * client)
Get the global associated with this client.
pw_client_get_info()
const struct pw_client_info* pw_client_get_info (struct pw_client * client)
Get the client information.
pw_client_get_properties()
const struct pw_properties* pw_client_get_properties (struct pw_client * client)
Get the client properties.
pw_client_get_user_data()
void* pw_client_get_user_data (struct pw_client * client)
Get the client user data.
pw_client_new()
struct pw_client* pw_client_new (struct pw_core * core, struct pw_properties * properties, size_t user_data_size)
Create a new client.
This is mainly used by protocols.
Parameters
core the core object
properties client properties
user_data_size extra user data size
pw_client_register()
int pw_client_register (struct pw_client * client, struct pw_client * owner, struct pw_global * parent, struct pw_properties * properties)
Finish configuration and register a client.
Parameters
client the client to register
owner optional owner
parent the client parent
properties extra properties
References pw_global::pw_global_new(), pw_log::pw_log_debug, PW_TYPE_INTERFACE_Client, and PW_VERSION_CLIENT_PROXY.
pw_client_set_busy()
void pw_client_set_busy (struct pw_client * client, bool busy)
Mark the client busy.
This can be used when an asynchronous operation is started and no further processing is allowed to happen for the client
References pw_log::pw_log_debug.
Referenced by pw_client_update_permissions().
pw_client_update_permissions()
int pw_client_update_permissions (struct pw_client * client, uint32_t n_permissions, const struct pw_permission * permissions)
Update the client permissions.
References pw_permission::id, pw_permission::permissions, pw_client_set_busy(), pw_core_find_global(), pw_global_update_permissions(), pw_log::pw_log_debug, and pw_log::pw_log_warn.
pw_client_update_properties()
int pw_client_update_properties (struct pw_client * client, const struct spa_dict * dict)
Update the client properties.