PipeWire: client.c File Reference
client.c File Reference
Functions
SPA_EXPORT int pw_client_register (struct pw_client *client, struct pw_client *owner, struct pw_global *parent, struct pw_properties *properties)
Finish configuration and register a client.
SPA_EXPORT struct pw_core * pw_client_get_core (struct pw_client *client)
Get the core used to create this client.
SPA_EXPORT struct pw_resource * pw_client_get_core_resource (struct pw_client *client)
Get the client core resource.
SPA_EXPORT struct pw_resource * pw_client_find_resource (struct pw_client *client, uint32_t id)
Get a resource with the given id.
SPA_EXPORT struct pw_global * pw_client_get_global (struct pw_client *client)
Get the global associated with this client.
SPA_EXPORT const struct pw_properties * pw_client_get_properties (struct pw_client *client)
Get the client properties.
SPA_EXPORT void * pw_client_get_user_data (struct pw_client *client)
Get the client user data.
SPA_EXPORT void pw_client_add_listener (struct pw_client *client, struct spa_hook *listener, const struct pw_client_events *events, void *data)
listen to events from this client
SPA_EXPORT const struct pw_client_info * pw_client_get_info (struct pw_client *client)
Get the client information.
SPA_EXPORT int pw_client_update_permissions (struct pw_client *client, uint32_t n_permissions, const struct pw_permission *permissions)
Update the client permissions.
SPA_EXPORT void pw_client_set_busy (struct pw_client *client, bool busy)
Mark the client busy.
Function Documentation
pw_client_add_listener()
SPA_EXPORT void pw_client_add_listener (struct pw_client * client, struct spa_hook * listener, const struct pw_client_events * events, void * data)
listen to events from this client
pw_client_find_resource()
SPA_EXPORT struct pw_resource* pw_client_find_resource (struct pw_client * client, uint32_t id)
Get a resource with the given id.
References pw_map::pw_map_lookup().
pw_client_get_core()
SPA_EXPORT struct pw_core* pw_client_get_core (struct pw_client * client)
Get the core used to create this client.
pw_client_get_core_resource()
SPA_EXPORT struct pw_resource* pw_client_get_core_resource (struct pw_client * client)
Get the client core resource.
pw_client_get_global()
SPA_EXPORT struct pw_global* pw_client_get_global (struct pw_client * client)
Get the global associated with this client.
pw_client_get_info()
SPA_EXPORT const struct pw_client_info* pw_client_get_info (struct pw_client * client)
Get the client information.
pw_client_get_properties()
SPA_EXPORT const struct pw_properties* pw_client_get_properties (struct pw_client * client)
Get the client properties.
pw_client_get_user_data()
SPA_EXPORT void* pw_client_get_user_data (struct pw_client * client)
Get the client user data.
pw_client_register()
SPA_EXPORT int pw_client_register (struct pw_client * client, struct pw_client * owner, struct pw_global * parent, struct pw_properties * properties)
Finish configuration and register a client.
Parameters
client the client to register
owner optional owner
parent the client parent
properties extra properties
References pw_global::pw_global_new(), pw_log::pw_log_debug, PW_TYPE_INTERFACE_Client, and PW_VERSION_CLIENT_PROXY.
pw_client_set_busy()
SPA_EXPORT void pw_client_set_busy (struct pw_client * client, bool busy)
Mark the client busy.
This can be used when an asynchronous operation is started and no further processing is allowed to happen for the client
References pw_log::pw_log_debug.
Referenced by pw_client_update_permissions().
pw_client_update_permissions()
SPA_EXPORT int pw_client_update_permissions (struct pw_client * client, uint32_t n_permissions, const struct pw_permission * permissions)
Update the client permissions.
References pw_permission::id, pw_permission::permissions, pw_client_set_busy(), pw_core_find_global(), pw_global_update_permissions(), pw_log::pw_log_debug, and pw_log::pw_log_warn.