PipeWire: control.c File Reference
control.c File Reference
Data Structures
struct impl
Functions
struct pw_control * pw_control_new (struct pw_core *core, struct pw_port *port, uint32_t id, uint32_t size, size_t user_data_size)
void pw_control_destroy (struct pw_control *control)
SPA_EXPORT struct pw_port * pw_control_get_port (struct pw_control *control)
Get the control parent port or NULL when not set.
SPA_EXPORT void pw_control_add_listener (struct pw_control *control, struct spa_hook *listener, const struct pw_control_events *events, void *data)
Add an event listener on the control.
SPA_EXPORT int pw_control_add_link (struct pw_control *control, uint32_t cmix, struct pw_control *other, uint32_t omix, struct pw_control_link *link)
SPA_EXPORT int pw_control_remove_link (struct pw_control_link *link)
Function Documentation
pw_control_add_link()
SPA_EXPORT int pw_control_add_link (struct pw_control * control, uint32_t cmix, struct pw_control * other, uint32_t omix, struct pw_control_link * link)
References control::id, impl::mem, pw_log::pw_log_debug, PW_MEMBLOCK_FLAG_MAP, PW_MEMBLOCK_FLAG_READWRITE, PW_MEMBLOCK_FLAG_SEAL, and pw_memblock::pw_mempool_alloc().
pw_control_add_listener()
SPA_EXPORT void pw_control_add_listener (struct pw_control * control, struct spa_hook * listener, const struct pw_control_events * events, void * data)
Add an event listener on the control.
pw_control_destroy()
void pw_control_destroy (struct pw_control * control)
References control::link, impl::mem, pw_control_remove_link(), and pw_log::pw_log_debug.
Referenced by pw_port_destroy().
pw_control_get_port()
SPA_EXPORT struct pw_port* pw_control_get_port (struct pw_control * control)
Get the control parent port or NULL when not set.
pw_control_new()
struct pw_control* pw_control_new (struct pw_core * core, struct pw_port * port, uint32_t id, uint32_t size, size_t user_data_size)
References pw_log::pw_log_debug, and impl::this.
pw_control_remove_link()
SPA_EXPORT int pw_control_remove_link (struct pw_control_link * link)
References pw_log::pw_log_debug.
Referenced by pw_control_destroy().