PipeWire: core.h File Reference
core.h File Reference
Data Structures
struct pw_core_events
core events emited by the core object added with pw_core_add_listener
Macros
#define PW_VERSION_CORE_EVENTS 0
Functions
struct pw_core * pw_core_new (struct pw_loop *main_loop, struct pw_properties *props, size_t user_data_size)
Make a new core object for a given main_loop.
void pw_core_destroy (struct pw_core *core)
destroy a core object, all resources except the main_loop will be destroyed
void * pw_core_get_user_data (struct pw_core *core)
Get the core user data.
void pw_core_add_listener (struct pw_core *core, struct spa_hook *listener, const struct pw_core_events *events, void *data)
Add a new event listener to a core.
const struct pw_core_info * pw_core_get_info (struct pw_core *core)
Get the core info object.
struct pw_global * pw_core_get_global (struct pw_core *core)
Get the core global object.
const struct pw_properties * pw_core_get_properties (struct pw_core *core)
Get the core properties.
int pw_core_update_properties (struct pw_core *core, const struct spa_dict *dict)
Update the core properties.
const struct spa_support * pw_core_get_support (struct pw_core *core, uint32_t *n_support)
Get the core support objects.
struct pw_loop * pw_core_get_main_loop (struct pw_core *core)
get the core main loop
int pw_core_for_each_global (struct pw_core *core, int(*callback)(void *data, struct pw_global *global), void *data)
Iterate the globals of the core.
struct pw_global * pw_core_find_global (struct pw_core *core, uint32_t id)
Find a core global by id.
struct pw_factory * pw_core_find_factory (struct pw_core *core, const char *name)
Find a factory by name.
int pw_core_add_spa_lib (struct pw_core *core, const char *factory_regex, const char *lib)
add a spa library for the given factory_name regex
const char * pw_core_find_spa_lib (struct pw_core *core, const char *factory_name)
find the library name for a spa factory
struct spa_handle * pw_core_load_spa_handle (struct pw_core *core, const char *factory_name, const struct spa_dict *info)
Macro Definition Documentation
PW_VERSION_CORE_EVENTS
#define PW_VERSION_CORE_EVENTS 0
Function Documentation
pw_core_add_listener()
void pw_core_add_listener (struct pw_core * core, struct spa_hook * listener, const struct pw_core_events * events, void * data)
Add a new event listener to a core.
pw_core_add_spa_lib()
int pw_core_add_spa_lib (struct pw_core * core, const char * factory_regex, const char * lib)
add a spa library for the given factory_name regex
References pw_array::pw_array_add(), pw_array_remove, pw_log::pw_log_debug, and pw_log::pw_log_error.
pw_core_destroy()
void pw_core_destroy (struct pw_core * core)
destroy a core object, all resources except the main_loop will be destroyed
pw_core_find_factory()
struct pw_factory* pw_core_find_factory (struct pw_core * core, const char * name)
Find a factory by name.
Parameters
core the core
name the factory name
pw_core_find_global()
struct pw_global* pw_core_find_global (struct pw_core * core, uint32_t id)
Find a core global by id.
Parameters
core the core
id the global id
References pw_global_get_permissions(), pw_map::pw_map_lookup(), and PW_PERM_IS_R.
Referenced by pw_client_update_permissions().
pw_core_find_spa_lib()
const char* pw_core_find_spa_lib (struct pw_core * core, const char * factory_name)
find the library name for a spa factory
References pw_array_for_each.
Referenced by pw_core_load_spa_handle().
pw_core_for_each_global()
int pw_core_for_each_global (struct pw_core * core, int(*)(void *data, struct pw_global *global) callback, void * data)
Iterate the globals of the core.
The callback should return 0 to fetch the next item, any other value stops the iteration and returns the value. When all callbacks return 0, this function returns 0 when all globals are iterated.
Parameters
core the core
References pw_global_get_permissions(), and PW_PERM_IS_R.
pw_core_get_global()
struct pw_global* pw_core_get_global (struct pw_core * core)
Get the core global object.
pw_core_get_info()
const struct pw_core_info* pw_core_get_info (struct pw_core * core)
Get the core info object.
pw_core_get_main_loop()
struct pw_loop* pw_core_get_main_loop (struct pw_core * core)
get the core main loop
pw_core_get_properties()
const struct pw_properties* pw_core_get_properties (struct pw_core * core)
Get the core properties.
pw_core_get_support()
const struct spa_support* pw_core_get_support (struct pw_core * core, uint32_t * n_support)
Get the core support objects.
Referenced by pw_core_load_spa_handle().
pw_core_get_user_data()
void* pw_core_get_user_data (struct pw_core * core)
Get the core user data.
pw_core_load_spa_handle()
struct spa_handle* pw_core_load_spa_handle (struct pw_core * core, const char * factory_name, const struct spa_dict * info)
References pw_core_find_spa_lib(), pw_core_get_support(), pw_load_spa_handle(), pw_log::pw_log_debug, and pw_log::pw_log_warn.
pw_core_new()
struct pw_core* pw_core_new (struct pw_loop * main_loop, struct pw_properties * props, size_t user_data_size)
Make a new core object for a given main_loop.
Ownership of the properties is taken
Parameters
main_loop a main loop to run in
props extra properties
user_data_size extra user data size
pw_core_update_properties()
int pw_core_update_properties (struct pw_core * core, const struct spa_dict * dict)
Update the core properties.