PipeWire: device.h File Reference
device.h File Reference
Data Structures
struct pw_device_events
Device events, listen to them with pw_device_add_listener.
Macros
#define PW_VERSION_DEVICE_EVENTS 0
Functions
struct pw_device * pw_device_new (struct pw_core *core, const char *name, struct pw_properties *properties, size_t user_data_size)
int pw_device_register (struct pw_device *device, struct pw_client *owner, struct pw_global *parent, struct pw_properties *properties)
void pw_device_destroy (struct pw_device *device)
void * pw_device_get_user_data (struct pw_device *device)
int pw_device_set_implementation (struct pw_device *device, struct spa_device *spa_device)
Set the device implementation.
struct spa_device * pw_device_get_implementation (struct pw_device *device)
Get the device implementation.
struct pw_global * pw_device_get_global (struct pw_device *device)
Get the global of this device.
void pw_device_add_listener (struct pw_device *device, struct spa_hook *listener, const struct pw_device_events *events, void *data)
Add an event listener.
int pw_device_update_properties (struct pw_device *device, const struct spa_dict *dict)
const struct pw_properties * pw_device_get_properties (struct pw_device *device)
int pw_device_for_each_param (struct pw_device *device, int seq, uint32_t param_id, uint32_t index, uint32_t max, const struct spa_pod *filter, int(*callback)(void *data, int seq, uint32_t id, uint32_t index, uint32_t next, struct spa_pod *param), void *data)
Macro Definition Documentation
PW_VERSION_DEVICE_EVENTS
#define PW_VERSION_DEVICE_EVENTS 0
Function Documentation
pw_device_add_listener()
void pw_device_add_listener (struct pw_device * device, struct spa_hook * listener, const struct pw_device_events * events, void * data)
Add an event listener.
pw_device_destroy()
void pw_device_destroy (struct pw_device * device)
References node_data::link, NAME, node_data::node, pw_global::pw_global_destroy(), pw_log::pw_log_debug, pw_node::pw_node_destroy(), and pw_properties::pw_properties_free().
Referenced by pw_core::pw_core_destroy().
pw_device_for_each_param()
int pw_device_for_each_param (struct pw_device * device, int seq, uint32_t param_id, uint32_t index, uint32_t max, const struct spa_pod * filter, int(*)(void *data, int seq, uint32_t id, uint32_t index, uint32_t next, struct spa_pod *param) callback, void * data)
References result_device_params_data::callback, and result_device_params_data::data.
pw_device_get_global()
struct pw_global* pw_device_get_global (struct pw_device * device)
Get the global of this device.
pw_device_get_implementation()
struct spa_device* pw_device_get_implementation (struct pw_device * device)
Get the device implementation.
pw_device_get_properties()
const struct pw_properties* pw_device_get_properties (struct pw_device * device)
pw_device_get_user_data()
void* pw_device_get_user_data (struct pw_device * device)
pw_device_new()
struct pw_device* pw_device_new (struct pw_core * core, const char * name, struct pw_properties * properties, size_t user_data_size)
References pw_properties::dict, NAME, pw_log::pw_log_debug, pw_properties::pw_properties_free(), pw_properties::pw_properties_new(), and impl::this.
pw_device_register()
int pw_device_register (struct pw_device * device, struct pw_client * owner, struct pw_global * parent, struct pw_properties * properties)
References pw_global::pw_global_new(), PW_KEY_DEVICE_NAME, PW_KEY_MEDIA_CLASS, pw_properties::pw_properties_get(), pw_properties::pw_properties_new(), pw_properties::pw_properties_set(), PW_TYPE_INTERFACE_Device, and PW_VERSION_DEVICE_PROXY.
pw_device_set_implementation()
int pw_device_set_implementation (struct pw_device * device, struct spa_device * spa_device)
Set the device implementation.
References NAME, pw_log::pw_log_debug, and pw_log::pw_log_error.
pw_device_update_properties()
int pw_device_update_properties (struct pw_device * device, const struct spa_dict * dict)