PipeWire: factory.c File Reference
factory.c File Reference
Data Structures
struct resource_data
Macros
#define NAME "factory"
#define pw_factory_resource_info(r, ...) pw_resource_call(r,struct pw_factory_proxy_events,info,0,__VA_ARGS__)
Functions
SPA_EXPORT struct pw_factory * pw_factory_new (struct pw_core *core, const char *name, uint32_t type, uint32_t version, struct pw_properties *properties, size_t user_data_size)
SPA_EXPORT void pw_factory_destroy (struct pw_factory *factory)
SPA_EXPORT int pw_factory_register (struct pw_factory *factory, struct pw_client *owner, struct pw_global *parent, struct pw_properties *properties)
SPA_EXPORT void * pw_factory_get_user_data (struct pw_factory *factory)
SPA_EXPORT struct pw_global * pw_factory_get_global (struct pw_factory *factory)
Get the global of this factory.
SPA_EXPORT void pw_factory_add_listener (struct pw_factory *factory, struct spa_hook *listener, const struct pw_factory_events *events, void *data)
Add an event listener.
SPA_EXPORT void pw_factory_set_implementation (struct pw_factory *factory, const struct pw_factory_implementation *implementation, void *data)
SPA_EXPORT void * pw_factory_create_object (struct pw_factory *factory, struct pw_resource *resource, uint32_t type, uint32_t version, struct pw_properties *properties, uint32_t new_id)
Macro Definition Documentation
NAME
#define NAME "factory"
pw_factory_resource_info
#define pw_factory_resource_info (r, ...) pw_resource_call(r,struct pw_factory_proxy_events,info,0,__VA_ARGS__)
Function Documentation
pw_factory_add_listener()
SPA_EXPORT void pw_factory_add_listener (struct pw_factory * factory, struct spa_hook * listener, const struct pw_factory_events * events, void * data)
Add an event listener.
pw_factory_create_object()
SPA_EXPORT void* pw_factory_create_object (struct pw_factory * factory, struct pw_resource * resource, uint32_t type, uint32_t version, struct pw_properties * properties, uint32_t new_id)
pw_factory_destroy()
SPA_EXPORT void pw_factory_destroy (struct pw_factory * factory)
References NAME, pw_global::pw_global_destroy(), pw_log::pw_log_debug, and pw_properties::pw_properties_free().
pw_factory_get_global()
SPA_EXPORT struct pw_global* pw_factory_get_global (struct pw_factory * factory)
Get the global of this factory.
pw_factory_get_user_data()
SPA_EXPORT void* pw_factory_get_user_data (struct pw_factory * factory)
pw_factory_new()
SPA_EXPORT struct pw_factory* pw_factory_new (struct pw_core * core, const char * name, uint32_t type, uint32_t version, struct pw_properties * properties, size_t user_data_size)
References pw_properties::dict, NAME, and pw_log::pw_log_debug.
pw_factory_register()
SPA_EXPORT int pw_factory_register (struct pw_factory * factory, struct pw_client * owner, struct pw_global * parent, struct pw_properties * properties)
References pw_global::pw_global_new(), PW_KEY_FACTORY_NAME, PW_KEY_FACTORY_TYPE_NAME, PW_KEY_FACTORY_TYPE_VERSION, pw_properties::pw_properties_new(), pw_properties::pw_properties_set(), pw_properties::pw_properties_setf(), pw_type_info(), PW_TYPE_INTERFACE_Factory, and PW_VERSION_FACTORY_PROXY.
pw_factory_set_implementation()
SPA_EXPORT void pw_factory_set_implementation (struct pw_factory * factory, const struct pw_factory_implementation * implementation, void * data)