PipeWire: global.c File Reference
global.c File Reference
Functions
SPA_EXPORT uint32_t pw_global_get_permissions (struct pw_global *global, struct pw_client *client)
Get the permissions of the global for a given client.
SPA_EXPORT struct pw_core * pw_global_get_core (struct pw_global *global)
Get the core object of this global.
SPA_EXPORT struct pw_client * pw_global_get_owner (struct pw_global *global)
Get the owner of the global.
SPA_EXPORT struct pw_global * pw_global_get_parent (struct pw_global *global)
Get the parent of a global.
SPA_EXPORT uint32_t pw_global_get_type (struct pw_global *global)
Get the global type.
SPA_EXPORT uint32_t pw_global_get_version (struct pw_global *global)
Get the global version.
SPA_EXPORT const struct pw_properties * pw_global_get_properties (struct pw_global *global)
Get the global properties.
SPA_EXPORT void * pw_global_get_object (struct pw_global *global)
Get the object associated with the global.
SPA_EXPORT uint32_t pw_global_get_id (struct pw_global *global)
Get the unique id of the global.
SPA_EXPORT void pw_global_add_listener (struct pw_global *global, struct spa_hook *listener, const struct pw_global_events *events, void *data)
Add an event listener on the global.
SPA_EXPORT int pw_global_update_permissions (struct pw_global *global, struct pw_client *client, uint32_t old_permissions, uint32_t new_permissions)
Function Documentation
pw_global_add_listener()
SPA_EXPORT void pw_global_add_listener (struct pw_global * global, struct spa_hook * listener, const struct pw_global_events * events, void * data)
Add an event listener on the global.
pw_global_get_core()
SPA_EXPORT struct pw_core* pw_global_get_core (struct pw_global * global)
Get the core object of this global.
pw_global_get_id()
SPA_EXPORT uint32_t pw_global_get_id (struct pw_global * global)
Get the unique id of the global.
pw_global_get_object()
SPA_EXPORT void* pw_global_get_object (struct pw_global * global)
Get the object associated with the global.
This depends on the type of the global
pw_global_get_owner()
SPA_EXPORT struct pw_client* pw_global_get_owner (struct pw_global * global)
Get the owner of the global.
This can be NULL when the core is owner
pw_global_get_parent()
SPA_EXPORT struct pw_global* pw_global_get_parent (struct pw_global * global)
Get the parent of a global.
pw_global_get_permissions()
SPA_EXPORT uint32_t pw_global_get_permissions (struct pw_global * global, struct pw_client * client)
Get the permissions of the global for a given client.
References PW_PERM_RWX.
Referenced by pw_core_find_global(), pw_core::pw_core_find_port(), pw_core_for_each_global(), and pw_global::pw_global_register().
pw_global_get_properties()
SPA_EXPORT const struct pw_properties* pw_global_get_properties (struct pw_global * global)
Get the global properties.
pw_global_get_type()
SPA_EXPORT uint32_t pw_global_get_type (struct pw_global * global)
Get the global type.
pw_global_get_version()
SPA_EXPORT uint32_t pw_global_get_version (struct pw_global * global)
Get the global version.
pw_global_update_permissions()
SPA_EXPORT int pw_global_update_permissions (struct pw_global * global, struct pw_client * client, uint32_t old_permissions, uint32_t new_permissions)
References pw_log::pw_log_debug, PW_PERM_IS_R, and pw_resource_destroy().
Referenced by pw_client_update_permissions().