PipeWire: global.h File Reference
global.h File Reference
Data Structures
struct pw_global_events
Global events, use pw_global_add_listener.
Macros
#define PW_VERSION_GLOBAL_EVENTS 0
Typedefs
typedef int(* pw_global_bind_func_t) (void *object, struct pw_client *client, uint32_t permissions, uint32_t version, uint32_t id)
Functions
struct pw_global * pw_global_new (struct pw_core *core, uint32_t type, uint32_t version, struct pw_properties *properties, pw_global_bind_func_t func, void *object)
Create a new global object.
int pw_global_register (struct pw_global *global, struct pw_client *owner, struct pw_global *parent)
Register a global object to the core registry.
void pw_global_add_listener (struct pw_global *global, struct spa_hook *listener, const struct pw_global_events *events, void *data)
Add an event listener on the global.
uint32_t pw_global_get_permissions (struct pw_global *global, struct pw_client *client)
Get the permissions of the global for a given client.
struct pw_core * pw_global_get_core (struct pw_global *global)
Get the core object of this global.
struct pw_client * pw_global_get_owner (struct pw_global *global)
Get the owner of the global.
struct pw_global * pw_global_get_parent (struct pw_global *global)
Get the parent of a global.
uint32_t pw_global_get_type (struct pw_global *global)
Get the global type.
uint32_t pw_global_get_version (struct pw_global *global)
Get the global version.
const struct pw_properties * pw_global_get_properties (struct pw_global *global)
Get the global properties.
void * pw_global_get_object (struct pw_global *global)
Get the object associated with the global.
uint32_t pw_global_get_id (struct pw_global *global)
Get the unique id of the global.
int pw_global_bind (struct pw_global *global, struct pw_client *client, uint32_t permissions, uint32_t version, uint32_t id)
Let a client bind to a global.
int pw_global_update_permissions (struct pw_global *global, struct pw_client *client, uint32_t old_permissions, uint32_t new_permissions)
void pw_global_destroy (struct pw_global *global)
Destroy a global.
Macro Definition Documentation
PW_VERSION_GLOBAL_EVENTS
#define PW_VERSION_GLOBAL_EVENTS 0
Typedef Documentation
pw_global_bind_func_t
typedef int(* pw_global_bind_func_t) (void *object, struct pw_client *client, uint32_t permissions, uint32_t version, uint32_t id)
Function Documentation
pw_global_add_listener()
void pw_global_add_listener (struct pw_global * global, struct spa_hook * listener, const struct pw_global_events * events, void * data)
Add an event listener on the global.
pw_global_bind()
int pw_global_bind (struct pw_global * global, struct pw_client * client, uint32_t permissions, uint32_t version, uint32_t id)
Let a client bind to a global.
pw_global_destroy()
void pw_global_destroy (struct pw_global * global)
Destroy a global.
pw_global_get_core()
struct pw_core* pw_global_get_core (struct pw_global * global)
Get the core object of this global.
pw_global_get_id()
uint32_t pw_global_get_id (struct pw_global * global)
Get the unique id of the global.
pw_global_get_object()
void* pw_global_get_object (struct pw_global * global)
Get the object associated with the global.
This depends on the type of the global
pw_global_get_owner()
struct pw_client* pw_global_get_owner (struct pw_global * global)
Get the owner of the global.
This can be NULL when the core is owner
pw_global_get_parent()
struct pw_global* pw_global_get_parent (struct pw_global * global)
Get the parent of a global.
pw_global_get_permissions()
uint32_t pw_global_get_permissions (struct pw_global * global, struct pw_client * client)
Get the permissions of the global for a given client.
References PW_PERM_RWX.
Referenced by pw_core_find_global(), pw_core::pw_core_find_port(), pw_core_for_each_global(), and pw_global::pw_global_register().
pw_global_get_properties()
const struct pw_properties* pw_global_get_properties (struct pw_global * global)
Get the global properties.
pw_global_get_type()
uint32_t pw_global_get_type (struct pw_global * global)
Get the global type.
pw_global_get_version()
uint32_t pw_global_get_version (struct pw_global * global)
Get the global version.
pw_global_new()
struct pw_global* pw_global_new (struct pw_core * core, uint32_t type, uint32_t version, struct pw_properties * properties, pw_global_bind_func_t func, void * object)
Create a new global object.
Parameters
core the core
type the interface type of the global
version the interface version of the global
properties extra properties
func function to bind
object global object
pw_global_register()
int pw_global_register (struct pw_global * global, struct pw_client * owner, struct pw_global * parent)
Register a global object to the core registry.
pw_global_update_permissions()
int pw_global_update_permissions (struct pw_global * global, struct pw_client * client, uint32_t old_permissions, uint32_t new_permissions)
References pw_log::pw_log_debug, PW_PERM_IS_R, and pw_resource_destroy().
Referenced by pw_client_update_permissions().