PipeWire: link.h File Reference
link.h File Reference
Data Structures
struct pw_link_events
link events added with pw_link_add_listener
Macros
#define PW_VERSION_LINK_EVENTS 0
Functions
void pw_link_add_listener (struct pw_link *link, struct spa_hook *listener, const struct pw_link_events *events, void *data)
Add an event listener to link.
int pw_link_register (struct pw_link *link, struct pw_client *owner, struct pw_global *parent, struct pw_properties *properties)
Finish link configuration and register.
struct pw_core * pw_link_get_core (struct pw_link *link)
Get the core of a link.
void * pw_link_get_user_data (struct pw_link *link)
Get the user_data of a link, the size of the memory is given when constructing the link.
const struct pw_link_info * pw_link_get_info (struct pw_link *link)
Get the link info.
struct pw_global * pw_link_get_global (struct pw_link *link)
Get the global of the link.
struct pw_port * pw_link_get_output (struct pw_link *link)
Get the output port of the link.
struct pw_port * pw_link_get_input (struct pw_link *link)
Get the input port of the link.
Macro Definition Documentation
PW_VERSION_LINK_EVENTS
#define PW_VERSION_LINK_EVENTS 0
Function Documentation
pw_link_add_listener()
void pw_link_add_listener (struct pw_link * link, struct spa_hook * listener, const struct pw_link_events * events, void * data)
Add an event listener to link.
References pw_log::pw_log_debug.
pw_link_get_core()
struct pw_core* pw_link_get_core (struct pw_link * link)
Get the core of a link.
pw_link_get_global()
struct pw_global* pw_link_get_global (struct pw_link * link)
Get the global of the link.
pw_link_get_info()
const struct pw_link_info* pw_link_get_info (struct pw_link * link)
Get the link info.
pw_link_get_input()
struct pw_port* pw_link_get_input (struct pw_link * link)
Get the input port of the link.
pw_link_get_output()
struct pw_port* pw_link_get_output (struct pw_link * link)
Get the output port of the link.
pw_link_get_user_data()
void* pw_link_get_user_data (struct pw_link * link)
Get the user_data of a link, the size of the memory is given when constructing the link.
pw_link_register()
int pw_link_register (struct pw_link * link, struct pw_client * owner, struct pw_global * parent, struct pw_properties * properties)
Finish link configuration and register.
Parameters
link the link to register
owner optional link owner
parent parent global
properties extra properties
References pw_global::pw_global_new(), PW_KEY_LINK_INPUT_PORT, PW_KEY_LINK_OUTPUT_PORT, pw_properties::pw_properties_new(), pw_properties::pw_properties_setf(), PW_TYPE_INTERFACE_Link, and PW_VERSION_LINK_PROXY.