PipeWire: mem.h File Reference
mem.h File Reference
Data Structures
struct pw_mempool
class pw_memblock
Memory block structure.
struct pw_memmap
a mapped region of a pw_memblock
struct pw_mempool_events
struct pw_map_range
parameters to map a memory range
Macros
#define PW_VERSION_MEMPOOL_EVENTS 0
#define PW_MAP_RANGE_INIT (struct pw_map_range){ 0, }
Enumerations
enum pw_memmap_flags {
PW_MEMMAP_FLAG_NONE = 0,
PW_MEMMAP_FLAG_READ = (1 << 0),
PW_MEMMAP_FLAG_WRITE = (1 << 1),
PW_MEMMAP_FLAG_TWICE = (1 << 2),
PW_MEMMAP_FLAG_READWRITE = PW_MEMMAP_FLAG_READ | PW_MEMMAP_FLAG_WRITE
}
Functions
struct pw_mempool * pw_mempool_new (struct pw_properties *props)
Create a new memory pool.
void pw_mempool_add_listener (struct pw_mempool *pool, struct spa_hook *listener, const struct pw_mempool_events *events, void *data)
Listen for events.
void pw_mempool_destroy (struct pw_mempool *pool)
Destroy a pool.
struct pw_memblock * pw_mempool_alloc (struct pw_mempool *pool, enum pw_memblock_flags flags, uint32_t type, size_t size)
Allocate a memory block from the pool.
struct pw_memblock * pw_mempool_import_block (struct pw_mempool *pool, struct pw_memblock *mem)
Import a block from another pool.
struct pw_memblock * pw_mempool_import (struct pw_mempool *pool, enum pw_memblock_flags flags, uint32_t type, int fd)
Import an fd into the pool.
void pw_memblock_free (struct pw_memblock *mem)
Free a memblock regardless of the refcount and destroy all mappings.
int pw_mempool_unref_id (struct pw_mempool *pool, uint32_t id)
Unref a memblock for given id.
struct pw_memblock * pw_mempool_find_ptr (struct pw_mempool *pool, const void *ptr)
Find memblock for given ptr.
struct pw_memblock * pw_mempool_find_id (struct pw_mempool *pool, uint32_t id)
Find memblock for given id.
struct pw_memblock * pw_mempool_find_fd (struct pw_mempool *pool, int fd)
Find memblock for given fd.
struct pw_memmap * pw_memblock_map (struct pw_memblock *block, enum pw_memmap_flags flags, uint32_t offset, uint32_t size, uint32_t tag[5])
Map a region of a memory block.
struct pw_memmap * pw_mempool_map_id (struct pw_mempool *pool, uint32_t id, enum pw_memmap_flags flags, uint32_t offset, uint32_t size, uint32_t tag[5])
Map a region of a memory block with id.
struct pw_memmap * pw_mempool_import_map (struct pw_mempool *pool, struct pw_mempool *other, void *data, uint32_t size, uint32_t tag[5])
struct pw_memmap * pw_mempool_find_tag (struct pw_mempool *pool, uint32_t tag[5], size_t size)
find a map with the given tag
int pw_memmap_free (struct pw_memmap *map)
Unmap a region.
Macro Definition Documentation
PW_MAP_RANGE_INIT
#define PW_MAP_RANGE_INIT (struct pw_map_range){ 0, }
PW_VERSION_MEMPOOL_EVENTS
#define PW_VERSION_MEMPOOL_EVENTS 0
Enumeration Type Documentation
pw_memmap_flags
enum pw_memmap_flags
Enumerator
PW_MEMMAP_FLAG_NONE
PW_MEMMAP_FLAG_READ
map in read mode
PW_MEMMAP_FLAG_WRITE
map in write mode
PW_MEMMAP_FLAG_TWICE
map the same area twice afer eachother, creating a circular ringbuffer
PW_MEMMAP_FLAG_READWRITE
Function Documentation
pw_memblock_free()
void pw_memblock_free (struct pw_memblock * mem)
Free a memblock regardless of the refcount and destroy all mappings.
pw_memblock_map()
struct pw_memmap* pw_memblock_map (struct pw_memblock * block, enum pw_memmap_flags flags, uint32_t offset, uint32_t size, uint32_t tag[5])
Map a region of a memory block.
References pw_memblock::pool.
Referenced by pw_memblock::pw_mempool_alloc(), and pw_mempool_map_id().
pw_memmap_free()
int pw_memmap_free (struct pw_memmap * map)
Unmap a region.
References mapping::block, pw_memblock::fd, memmap::link, memmap::mapping, pw_memblock::pool, pw_memmap::ptr, pw_log::pw_log_debug, mapping::ref, memblock::this, and memmap::this.
Referenced by pw_memblock::pw_memblock_free().
pw_mempool_add_listener()
void pw_mempool_add_listener (struct pw_mempool * pool, struct spa_hook * listener, const struct pw_mempool_events * events, void * data)
Listen for events.
Referenced by pw_client::pw_client_new().
pw_mempool_alloc()
struct pw_memblock* pw_mempool_alloc (struct pw_mempool * pool, enum pw_memblock_flags flags, uint32_t type, size_t size)
Allocate a memory block from the pool.
pw_mempool_destroy()
void pw_mempool_destroy (struct pw_mempool * pool)
Destroy a pool.
References memblock::link, pw_mempool::props, pw_log::pw_log_debug, pw_memblock::pw_memblock_free(), pw_mempool_emit_destroy, pw_properties::pw_properties_free(), and memblock::this.
Referenced by pw_core::pw_core_destroy(), and pw_remote_destroy().
pw_mempool_find_fd()
struct pw_memblock* pw_mempool_find_fd (struct pw_mempool * pool, int fd)
Find memblock for given fd.
pw_mempool_find_id()
struct pw_memblock* pw_mempool_find_id (struct pw_mempool * pool, uint32_t id)
Find memblock for given id.
References pw_log::pw_log_debug, pw_map::pw_map_lookup(), and memblock::this.
pw_mempool_find_ptr()
struct pw_memblock* pw_mempool_find_ptr (struct pw_mempool * pool, const void * ptr)
Find memblock for given ptr.
References mapping::block, pw_memblock::id, mapping::link, memblock::mappings, mapping::ptr, pw_log::pw_log_debug, mapping::size, and memblock::this.
Referenced by pw_mempool_import_map().
pw_mempool_find_tag()
struct pw_memmap* pw_mempool_find_tag (struct pw_mempool * pool, uint32_t tag[5], size_t size)
find a map with the given tag
References memmap::link, memblock::maps, pw_log::pw_log_debug, pw_memmap::tag, and memmap::this.
pw_mempool_import()
struct pw_memblock* pw_mempool_import (struct pw_mempool * pool, enum pw_memblock_flags flags, uint32_t type, int fd)
Import an fd into the pool.
Referenced by pw_mempool_import_block().
pw_mempool_import_block()
struct pw_memblock* pw_mempool_import_block (struct pw_mempool * pool, struct pw_memblock * mem)
Import a block from another pool.
References pw_memblock::fd, pw_memblock::flags, pw_memblock::pool, PW_MEMBLOCK_FLAG_DONT_CLOSE, pw_mempool_import(), and pw_memblock::type.
Referenced by pw_mempool_import_map().
pw_mempool_import_map()
struct pw_memmap* pw_mempool_import_map (struct pw_mempool * pool, struct pw_mempool * other, void * data, uint32_t size, uint32_t tag[5])
References mapping::block, pw_memblock::map, mapping::offset, pw_mempool_find_ptr(), and pw_mempool_import_block().
pw_mempool_map_id()
struct pw_memmap* pw_mempool_map_id (struct pw_mempool * pool, uint32_t id, enum pw_memmap_flags flags, uint32_t offset, uint32_t size, uint32_t tag[5])
Map a region of a memory block with id.
References pw_map::pw_map_lookup(), pw_memblock_map(), and memblock::this.
pw_mempool_new()
struct pw_mempool* pw_mempool_new (struct pw_properties * props)
Create a new memory pool.
References pw_mempool::props, pw_log::pw_log_debug, pw_map::pw_map_init(), and impl::this.
Referenced by pw_client::pw_client_new(), pw_core::pw_core_new(), and pw_remote_new().
pw_mempool_unref_id()
int pw_mempool_unref_id (struct pw_mempool * pool, uint32_t id)
Unref a memblock for given id.
References pw_map::pw_map_lookup().