PipeWire: node.h File Reference
node.h File Reference
Data Structures
struct pw_node_events
Node events, listen to them with pw_node_add_listener.
Macros
#define PW_VERSION_NODE_EVENTS 0
Functions
int pw_node_register (struct pw_node *node, struct pw_client *owner, struct pw_global *parent, struct pw_properties *properties)
Complete initialization of the node and register.
void pw_node_destroy (struct pw_node *node)
Destroy a node.
const struct pw_node_info * pw_node_get_info (struct pw_node *node)
Get the node info.
void * pw_node_get_user_data (struct pw_node *node)
Get node user_data.
struct pw_core * pw_node_get_core (struct pw_node *node)
Get the core of this node.
struct pw_global * pw_node_get_global (struct pw_node *node)
Get the global of this node.
const struct pw_properties * pw_node_get_properties (struct pw_node *node)
Get the node properties.
int pw_node_update_properties (struct pw_node *node, const struct spa_dict *dict)
Update the node properties.
int pw_node_set_implementation (struct pw_node *node, struct spa_node *spa_node)
Set the node implementation.
struct spa_node * pw_node_get_implementation (struct pw_node *node)
Get the node implementation.
void pw_node_add_listener (struct pw_node *node, struct spa_hook *listener, const struct pw_node_events *events, void *data)
Add an event listener.
int pw_node_for_each_port (struct pw_node *node, enum pw_direction direction, int(*callback)(void *data, struct pw_port *port), void *data)
Iterate the ports in the given direction.
int pw_node_for_each_param (struct pw_node *node, int seq, uint32_t param_id, uint32_t index, uint32_t max, const struct spa_pod *filter, int(*callback)(void *data, int seq, uint32_t id, uint32_t index, uint32_t next, struct spa_pod *param), void *data)
struct pw_port * pw_node_find_port (struct pw_node *node, enum pw_direction direction, uint32_t port_id)
Find the port with direction and port_id or NULL when not found.
uint32_t pw_node_get_free_port_id (struct pw_node *node, enum pw_direction direction)
Get a free unused port_id from the node.
int pw_node_set_active (struct pw_node *node, bool active)
Set a node active.
bool pw_node_is_active (struct pw_node *node)
Check if a node is active.
Macro Definition Documentation
PW_VERSION_NODE_EVENTS
#define PW_VERSION_NODE_EVENTS 0
Function Documentation
pw_node_add_listener()
void pw_node_add_listener (struct pw_node * node, struct spa_hook * listener, const struct pw_node_events * events, void * data)
Add an event listener.
pw_node_destroy()
void pw_node_destroy (struct pw_node * node)
Destroy a node.
pw_node_find_port()
struct pw_port* pw_node_find_port (struct pw_node * node, enum pw_direction direction, uint32_t port_id)
Find the port with direction and port_id or NULL when not found.
Passing SPA_ID_INVALID for port_id will return any port, preferably an unlinked one.
References pw_introspect::pw_direction_as_string(), PW_DIRECTION_INPUT, pw_log::pw_log_debug, and pw_map::pw_map_lookup().
Referenced by pw_core::pw_core_find_port().
pw_node_for_each_param()
int pw_node_for_each_param (struct pw_node * node, int seq, uint32_t param_id, uint32_t index, uint32_t max, const struct spa_pod * filter, int(*)(void *data, int seq, uint32_t id, uint32_t index, uint32_t next, struct spa_pod *param) callback, void * data)
References result_node_params_data::callback, result_node_params_data::data, and result_node_params_data::seq.
pw_node_for_each_port()
int pw_node_for_each_port (struct pw_node * node, enum pw_direction direction, int(*)(void *data, struct pw_port *port) callback, void * data)
Iterate the ports in the given direction.
The callback should return 0 to fetch the next item, any other value stops the iteration and returns the value. When all callbacks return 0, this function returns 0 when all items are iterated.
References PW_DIRECTION_INPUT.
pw_node_get_core()
struct pw_core* pw_node_get_core (struct pw_node * node)
Get the core of this node.
pw_node_get_free_port_id()
uint32_t pw_node_get_free_port_id (struct pw_node * node, enum pw_direction direction)
Get a free unused port_id from the node.
References pw_introspect::pw_direction_as_string(), PW_DIRECTION_INPUT, pw_log::pw_log_debug, pw_log::pw_log_warn, and pw_map::pw_map_insert_new().
pw_node_get_global()
struct pw_global* pw_node_get_global (struct pw_node * node)
Get the global of this node.
pw_node_get_implementation()
struct spa_node* pw_node_get_implementation (struct pw_node * node)
Get the node implementation.
pw_node_get_info()
const struct pw_node_info* pw_node_get_info (struct pw_node * node)
Get the node info.
pw_node_get_properties()
const struct pw_properties* pw_node_get_properties (struct pw_node * node)
Get the node properties.
pw_node_get_user_data()
void* pw_node_get_user_data (struct pw_node * node)
Get node user_data.
The size of the memory was given in pw_node_new
pw_node_is_active()
bool pw_node_is_active (struct pw_node * node)
Check if a node is active.
pw_node_register()
int pw_node_register (struct pw_node * node, struct pw_client * owner, struct pw_global * parent, struct pw_properties * properties)
Complete initialization of the node and register.
Parameters
node node to register
owner optional owner
parent optional parent
properties extra properties
References pw_global::pw_global_new(), PW_KEY_MEDIA_CLASS, PW_KEY_MEDIA_ROLE, PW_KEY_NODE_NAME, PW_KEY_NODE_SESSION, pw_log::pw_log_debug, pw_properties::pw_properties_get(), pw_properties::pw_properties_new(), pw_properties::pw_properties_set(), PW_TYPE_INTERFACE_Node, and PW_VERSION_NODE_PROXY.
pw_node_set_active()
int pw_node_set_active (struct pw_node * node, bool active)
Set a node active.
This will start negotiation with all linked active nodes and start data transport
References pw_log::pw_log_debug, pw_node::pw_node_set_state(), and PW_NODE_STATE_IDLE.
Referenced by pw_stream_set_active().
pw_node_set_implementation()
int pw_node_set_implementation (struct pw_node * node, struct spa_node * spa_node)
Set the node implementation.
References pw_log::pw_log_debug, and pw_log::pw_log_error.
pw_node_update_properties()
int pw_node_update_properties (struct pw_node * node, const struct spa_dict * dict)
Update the node properties.
Referenced by pw_stream_update_properties().