PipeWire: pipewire.c File Reference
pipewire.c File Reference
Data Structures
struct plugin
struct handle
struct registry
struct support
Macros
#define MAX_SUPPORT 32
#define SUPPORTLIB "support/libspa-support"
Functions
SPA_EXPORT uint32_t pw_get_support (struct spa_support *support, uint32_t max_support)
SPA_EXPORT struct spa_handle * pw_load_spa_handle (const char *lib, const char *factory_name, const struct spa_dict *info, uint32_t n_support, const struct spa_support support[])
SPA_EXPORT int pw_unload_spa_handle (struct spa_handle *handle)
SPA_EXPORT const char * pw_get_library_version (void)
Get the currently running version.
SPA_EXPORT const struct spa_type_info * pw_type_info (void)
Macro Definition Documentation
MAX_SUPPORT
#define MAX_SUPPORT 32
SUPPORTLIB
#define SUPPORTLIB "support/libspa-support"
Function Documentation
pw_get_library_version()
SPA_EXPORT const char* pw_get_library_version (void)
Get the currently running version.
Referenced by pw_core::pw_core_new().
pw_get_support()
SPA_EXPORT uint32_t pw_get_support (struct spa_support * support, uint32_t max_support)
Referenced by pw_core::pw_core_new(), and pw_loop::pw_loop_new().
pw_load_spa_handle()
SPA_EXPORT struct spa_handle* pw_load_spa_handle (const char * lib, const char * factory_name, const struct spa_dict * info, uint32_t n_support, const struct spa_support support[])
Referenced by pw_core_load_spa_handle(), pw_core::pw_core_new(), and pw_loop::pw_loop_new().
pw_type_info()
SPA_EXPORT const struct spa_type_info* pw_type_info (void)
Referenced by pw_core_register_export_type(), pw_factory_register(), pw_global::pw_global_new(), pw_protocol_add_marshal(), pw_proxy::pw_proxy_new(), and pw_resource_new().
pw_unload_spa_handle()
SPA_EXPORT int pw_unload_spa_handle (struct spa_handle * handle)
Referenced by pw_core::pw_core_destroy(), pw_loop::pw_loop_destroy(), and pw_loop::pw_loop_new().