PipeWire: port.c File Reference
port.c File Reference
Data Structures
struct result_port_params_data
struct param_filter
Functions
void pw_port_update_state (struct pw_port *port, enum pw_port_state state, char *error)
SPA_EXPORT int pw_port_init_mix (struct pw_port *port, struct pw_port_mix *mix)
SPA_EXPORT int pw_port_release_mix (struct pw_port *port, struct pw_port_mix *mix)
SPA_EXPORT struct pw_port * pw_port_new (enum pw_direction direction, uint32_t port_id, const struct spa_port_info *info, size_t user_data_size)
SPA_EXPORT int pw_port_set_mix (struct pw_port *port, struct spa_node *node, uint32_t flags)
SPA_EXPORT enum pw_direction pw_port_get_direction (struct pw_port *port)
Get the port direction.
SPA_EXPORT uint32_t pw_port_get_id (struct pw_port *port)
Get the port id.
SPA_EXPORT const struct pw_properties * pw_port_get_properties (struct pw_port *port)
Get the port properties.
SPA_EXPORT int pw_port_update_properties (struct pw_port *port, const struct spa_dict *dict)
Update the port properties.
void pw_port_update_info (struct pw_port *port, const struct spa_port_info *info)
SPA_EXPORT struct pw_node * pw_port_get_node (struct pw_port *port)
Get the port parent node or NULL when not yet set.
SPA_EXPORT void pw_port_add_listener (struct pw_port *port, struct spa_hook *listener, const struct pw_port_events *events, void *data)
Add an event listener on the port.
SPA_EXPORT void * pw_port_get_user_data (struct pw_port *port)
int pw_port_register (struct pw_port *port, struct pw_client *owner, struct pw_global *parent, struct pw_properties *properties)
SPA_EXPORT int pw_port_add (struct pw_port *port, struct pw_node *node)
void pw_port_unlink (struct pw_port *port)
void pw_port_destroy (struct pw_port *port)
int pw_port_for_each_param (struct pw_port *port, int seq, uint32_t param_id, uint32_t index, uint32_t max, const struct spa_pod *filter, int(*callback)(void *data, int seq, uint32_t id, uint32_t index, uint32_t next, struct spa_pod *param), void *data)
int pw_port_for_each_filtered_param (struct pw_port *in_port, struct pw_port *out_port, int seq, uint32_t in_param_id, uint32_t out_param_id, const struct spa_pod *filter, int(*callback)(void *data, int seq, uint32_t id, uint32_t index, uint32_t next, struct spa_pod *param), void *data)
int pw_port_for_each_link (struct pw_port *port, int(*callback)(void *data, struct pw_link *link), void *data)
SPA_EXPORT int pw_port_is_linked (struct pw_port *port)
SPA_EXPORT int pw_port_set_param (struct pw_port *port, uint32_t id, uint32_t flags, const struct spa_pod *param)
SPA_EXPORT int pw_port_use_buffers (struct pw_port *port, uint32_t mix_id, uint32_t flags, struct spa_buffer **buffers, uint32_t n_buffers)
SPA_EXPORT int pw_port_alloc_buffers (struct pw_port *port, struct spa_buffer **buffers, uint32_t n_buffers)
Function Documentation
pw_port_add()
SPA_EXPORT int pw_port_add (struct pw_port * port, struct pw_node * node)
References PW_DIRECTION_INPUT, pw_map::pw_map_insert_at(), pw_map::pw_map_lookup(), and pw_port_for_each_param().
pw_port_add_listener()
SPA_EXPORT void pw_port_add_listener (struct pw_port * port, struct spa_hook * listener, const struct pw_port_events * events, void * data)
Add an event listener on the port.
pw_port_alloc_buffers()
SPA_EXPORT int pw_port_alloc_buffers (struct pw_port * port, struct spa_buffer ** buffers, uint32_t n_buffers)
References pw_log::pw_log_debug, pw_log::pw_log_error, PW_PORT_STATE_PAUSED, PW_PORT_STATE_READY, and pw_port_update_state().
pw_port_destroy()
void pw_port_destroy (struct pw_port * port)
References pw_control_destroy(), and pw_log::pw_log_debug.
pw_port_for_each_filtered_param()
int pw_port_for_each_filtered_param (struct pw_port * in_port, struct pw_port * out_port, int seq, uint32_t in_param_id, uint32_t out_param_id, const struct spa_pod * filter, int(*)(void *data, int seq, uint32_t id, uint32_t index, uint32_t next, struct spa_pod *param) callback, void * data)
References param_filter::callback, param_filter::data, param_filter::in_param_id, param_filter::in_port, param_filter::out_param_id, param_filter::out_port, pw_port_for_each_param(), and param_filter::seq.
pw_port_for_each_link()
int pw_port_for_each_link (struct pw_port * port, int(*)(void *data, struct pw_link *link) callback, void * data)
References PW_DIRECTION_OUTPUT.
Referenced by pw_port_unlink().
pw_port_for_each_param()
int pw_port_for_each_param (struct pw_port * port, int seq, uint32_t param_id, uint32_t index, uint32_t max, const struct spa_pod * filter, int(*)(void *data, int seq, uint32_t id, uint32_t index, uint32_t next, struct spa_pod *param) callback, void * data)
References result_port_params_data::callback, result_port_params_data::data, and result_port_params_data::seq.
Referenced by pw_port_add(), and pw_port_for_each_filtered_param().
pw_port_get_direction()
SPA_EXPORT enum pw_direction pw_port_get_direction (struct pw_port * port)
Get the port direction.
pw_port_get_id()
SPA_EXPORT uint32_t pw_port_get_id (struct pw_port * port)
Get the port id.
pw_port_get_node()
SPA_EXPORT struct pw_node* pw_port_get_node (struct pw_port * port)
Get the port parent node or NULL when not yet set.
pw_port_get_properties()
SPA_EXPORT const struct pw_properties* pw_port_get_properties (struct pw_port * port)
Get the port properties.
pw_port_get_user_data()
SPA_EXPORT void* pw_port_get_user_data (struct pw_port * port)
pw_port_init_mix()
SPA_EXPORT int pw_port_init_mix (struct pw_port * port, struct pw_port_mix * mix)
References pw_pipewire::pw_direction_reverse(), pw_log::pw_log_debug, and pw_map::pw_map_insert_new().
pw_port_is_linked()
SPA_EXPORT int pw_port_is_linked (struct pw_port * port)
pw_port_new()
SPA_EXPORT struct pw_port* pw_port_new (enum pw_direction direction, uint32_t port_id, const struct spa_port_info * info, size_t user_data_size)
References pw_properties::dict, pw_introspect::pw_direction_as_string(), PW_DIRECTION_INPUT, PW_KEY_PORT_PHYSICAL, PW_KEY_PORT_TERMINAL, pw_log::pw_log_debug, PW_PORT_CHANGE_MASK_PROPS, PW_PORT_STATE_INIT, pw_properties::pw_properties_new(), pw_properties::pw_properties_new_dict(), pw_properties::pw_properties_set(), and impl::this.
pw_port_register()
int pw_port_register (struct pw_port * port, struct pw_client * owner, struct pw_global * parent, struct pw_properties * properties)
References pw_global::pw_global_new(), PW_TYPE_INTERFACE_Port, and PW_VERSION_PORT_PROXY.
pw_port_release_mix()
SPA_EXPORT int pw_port_release_mix (struct pw_port * port, struct pw_port_mix * mix)
References pw_log::pw_log_debug, and pw_map::pw_map_remove().
pw_port_set_mix()
SPA_EXPORT int pw_port_set_mix (struct pw_port * port, struct spa_node * node, uint32_t flags)
References pw_log::pw_log_debug.
pw_port_set_param()
SPA_EXPORT int pw_port_set_param (struct pw_port * port, uint32_t id, uint32_t flags, const struct spa_pod * param)
References pw_pipewire::pw_direction_reverse(), pw_log::pw_log_debug, PW_PORT_STATE_CONFIGURE, PW_PORT_STATE_READY, and pw_port_update_state().
pw_port_unlink()
void pw_port_unlink (struct pw_port * port)
References pw_port_for_each_link().
pw_port_update_info()
void pw_port_update_info (struct pw_port * port, const struct spa_port_info * info)
pw_port_update_properties()
SPA_EXPORT int pw_port_update_properties (struct pw_port * port, const struct spa_dict * dict)
Update the port properties.
pw_port_update_state()
void pw_port_update_state (struct pw_port * port, enum pw_port_state state, char * error)
References pw_log, and PW_PORT_STATE_ERROR.
Referenced by pw_port_alloc_buffers(), pw_port_set_param(), and pw_port_use_buffers().
pw_port_use_buffers()
SPA_EXPORT int pw_port_use_buffers (struct pw_port * port, uint32_t mix_id, uint32_t flags, struct spa_buffer ** buffers, uint32_t n_buffers)
References pw_log::pw_log_debug, pw_log::pw_log_error, pw_map::pw_map_lookup(), PW_PORT_STATE_PAUSED, PW_PORT_STATE_READY, and pw_port_update_state().