PipeWire: remote.c File Reference
remote.c File Reference
Functions
SPA_EXPORT const char * pw_remote_state_as_string (enum pw_remote_state state)
SPA_EXPORT struct pw_remote * pw_remote_new (struct pw_core *core, struct pw_properties *properties, size_t user_data_size)
SPA_EXPORT void pw_remote_destroy (struct pw_remote *remote)
SPA_EXPORT struct pw_core * pw_remote_get_core (struct pw_remote *remote)
Get the core used to construct this remote.
SPA_EXPORT const struct pw_properties * pw_remote_get_properties (struct pw_remote *remote)
Get the remote properties.
SPA_EXPORT int pw_remote_update_properties (struct pw_remote *remote, const struct spa_dict *dict)
Update properties.
SPA_EXPORT void * pw_remote_get_user_data (struct pw_remote *remote)
Get the user_data.
SPA_EXPORT enum pw_remote_state pw_remote_get_state (struct pw_remote *remote, const char **error)
Get the current state, error is set when state is PW_REMOTE_STATE_ERROR.
SPA_EXPORT void pw_remote_add_listener (struct pw_remote *remote, struct spa_hook *listener, const struct pw_remote_events *events, void *data)
Add listener for events.
SPA_EXPORT struct pw_core_proxy * pw_remote_get_core_proxy (struct pw_remote *remote)
Get the core proxy, can only be called when connected.
SPA_EXPORT struct pw_client_proxy * pw_remote_get_client_proxy (struct pw_remote *remote)
Get the client proxy, can only be called when connected.
SPA_EXPORT struct pw_proxy * pw_remote_find_proxy (struct pw_remote *remote, uint32_t id)
Get the proxy with the given id.
SPA_EXPORT int pw_remote_connect (struct pw_remote *remote)
SPA_EXPORT int pw_remote_connect_fd (struct pw_remote *remote, int fd)
SPA_EXPORT int pw_remote_steal_fd (struct pw_remote *remote)
Steal the fd of the remote connection or < 0 on error.
SPA_EXPORT int pw_remote_disconnect (struct pw_remote *remote)
SPA_EXPORT struct pw_proxy * pw_remote_export (struct pw_remote *remote, uint32_t type, struct pw_properties *props, void *object, size_t user_data_size)
run a local node in a remote graph
SPA_EXPORT int pw_core_register_export_type (struct pw_core *core, struct pw_export_type *type)
register a type that can be exported on a remote.
const struct pw_export_type * pw_core_find_export_type (struct pw_core *core, uint32_t type)
Function Documentation
pw_core_find_export_type()
const struct pw_export_type* pw_core_find_export_type (struct pw_core * core, uint32_t type)
References pw_export_type::link, and pw_export_type::type.
Referenced by pw_remote_export().
pw_core_register_export_type()
SPA_EXPORT int pw_core_register_export_type (struct pw_core * core, struct pw_export_type * type)
register a type that can be exported on a remote.
This is usually used by extension modules
References pw_log::pw_log_debug, pw_type_info(), and pw_export_type::type.
pw_remote_add_listener()
SPA_EXPORT void pw_remote_add_listener (struct pw_remote * remote, struct spa_hook * listener, const struct pw_remote_events * events, void * data)
Add listener for events.
pw_remote_connect()
SPA_EXPORT int pw_remote_connect (struct pw_remote * remote)
pw_remote_connect_fd()
SPA_EXPORT int pw_remote_connect_fd (struct pw_remote * remote, int fd)
pw_remote_destroy()
SPA_EXPORT void pw_remote_destroy (struct pw_remote * remote)
References pw_log::pw_log_debug, pw_map::pw_map_clear(), pw_mempool_destroy(), pw_properties::pw_properties_free(), pw_protocol_client_destroy, pw_remote::pw_remote_disconnect(), PW_REMOTE_STATE_UNCONNECTED, and pw_stream::pw_stream_destroy().
pw_remote_disconnect()
SPA_EXPORT int pw_remote_disconnect (struct pw_remote * remote)
References pw_log::pw_log_debug, pw_protocol_client_disconnect, and pw_stream::pw_stream_disconnect().
pw_remote_export()
SPA_EXPORT struct pw_proxy* pw_remote_export (struct pw_remote * remote, uint32_t type, struct pw_properties * props, void * object, size_t user_data_size)
run a local node in a remote graph
Parameters
remote the remote
type the type of object
props extra properties
object object to export
user_data_size extra user data
References pw_export_type::func, pw_core_find_export_type(), pw_log::pw_log_error, and pw_export_type::type.
pw_remote_find_proxy()
SPA_EXPORT struct pw_proxy* pw_remote_find_proxy (struct pw_remote * remote, uint32_t id)
Get the proxy with the given id.
References pw_map::pw_map_lookup().
pw_remote_get_client_proxy()
SPA_EXPORT struct pw_client_proxy* pw_remote_get_client_proxy (struct pw_remote * remote)
Get the client proxy, can only be called when connected.
pw_remote_get_core()
SPA_EXPORT struct pw_core* pw_remote_get_core (struct pw_remote * remote)
Get the core used to construct this remote.
pw_remote_get_core_proxy()
SPA_EXPORT struct pw_core_proxy* pw_remote_get_core_proxy (struct pw_remote * remote)
Get the core proxy, can only be called when connected.
pw_remote_get_properties()
SPA_EXPORT const struct pw_properties* pw_remote_get_properties (struct pw_remote * remote)
Get the remote properties.
Referenced by pw_stream_new().
pw_remote_get_state()
SPA_EXPORT enum pw_remote_state pw_remote_get_state (struct pw_remote * remote, const char ** error)
Get the current state, error is set when state is PW_REMOTE_STATE_ERROR.
pw_remote_get_user_data()
SPA_EXPORT void* pw_remote_get_user_data (struct pw_remote * remote)
Get the user_data.
The size was given in pw_remote_new
pw_remote_new()
SPA_EXPORT struct pw_remote* pw_remote_new (struct pw_core * core, struct pw_properties * properties, size_t user_data_size)
References pw_core_find_protocol(), pw_pipewire::pw_fill_remote_properties(), PW_KEY_PROTOCOL, pw_log::pw_log_debug, pw_log::pw_log_error, pw_map::pw_map_init(), pw_mempool_new(), pw_module::pw_module_load(), pw_properties::pw_properties_free(), pw_properties::pw_properties_get(), pw_properties::pw_properties_new(), pw_protocol_new_client, PW_REMOTE_STATE_UNCONNECTED, and impl::this.
pw_remote_state_as_string()
SPA_EXPORT const char* pw_remote_state_as_string (enum pw_remote_state state)
References PW_REMOTE_STATE_CONNECTED, PW_REMOTE_STATE_CONNECTING, PW_REMOTE_STATE_ERROR, and PW_REMOTE_STATE_UNCONNECTED.
pw_remote_steal_fd()
SPA_EXPORT int pw_remote_steal_fd (struct pw_remote * remote)
Steal the fd of the remote connection or < 0 on error.
The remote will be in the unconnected state after this call.
References pw_protocol_client_steal_fd.
pw_remote_update_properties()
SPA_EXPORT int pw_remote_update_properties (struct pw_remote * remote, const struct spa_dict * dict)
Update properties.
References pw_properties::dict, pw_client_proxy_update_properties, pw_log::pw_log_debug, and pw_properties::pw_properties_update().