PipeWire: remote.h File Reference
remote.h File Reference
Data Structures
struct pw_remote_events
Events for the remote.
struct pw_export_type
data for registering export functions
Macros
#define PW_VERSION_REMOTE_EVENTS 0
Enumerations
enum pw_remote_state {
PW_REMOTE_STATE_ERROR = -1,
PW_REMOTE_STATE_UNCONNECTED = 0,
PW_REMOTE_STATE_CONNECTING = 1,
PW_REMOTE_STATE_CONNECTED = 2
}
The state of a pw_remote.
Functions
struct pw_core * pw_remote_get_core (struct pw_remote *remote)
Get the core used to construct this remote.
const struct pw_properties * pw_remote_get_properties (struct pw_remote *remote)
Get the remote properties.
int pw_remote_update_properties (struct pw_remote *remote, const struct spa_dict *dict)
Update properties.
void * pw_remote_get_user_data (struct pw_remote *remote)
Get the user_data.
enum pw_remote_state pw_remote_get_state (struct pw_remote *remote, const char **error)
Get the current state, error is set when state is PW_REMOTE_STATE_ERROR.
void pw_remote_add_listener (struct pw_remote *remote, struct spa_hook *listener, const struct pw_remote_events *events, void *data)
Add listener for events.
int pw_remote_steal_fd (struct pw_remote *remote)
Steal the fd of the remote connection or < 0 on error.
struct pw_core_proxy * pw_remote_get_core_proxy (struct pw_remote *remote)
Get the core proxy, can only be called when connected.
struct pw_client_proxy * pw_remote_get_client_proxy (struct pw_remote *remote)
Get the client proxy, can only be called when connected.
struct pw_proxy * pw_remote_find_proxy (struct pw_remote *remote, uint32_t id)
Get the proxy with the given id.
struct pw_proxy * pw_remote_export (struct pw_remote *remote, uint32_t type, struct pw_properties *properties, void *object, size_t user_data_size)
run a local node in a remote graph
int pw_core_register_export_type (struct pw_core *core, struct pw_export_type *type)
register a type that can be exported on a remote.
Macro Definition Documentation
PW_VERSION_REMOTE_EVENTS
#define PW_VERSION_REMOTE_EVENTS 0
Enumeration Type Documentation
pw_remote_state
enum pw_remote_state
The state of a pw_remote.
Enumerator
PW_REMOTE_STATE_ERROR
remote is in error
PW_REMOTE_STATE_UNCONNECTED
not connected
PW_REMOTE_STATE_CONNECTING
connecting to remote PipeWire
PW_REMOTE_STATE_CONNECTED
remote is connected and ready
Function Documentation
pw_core_register_export_type()
int pw_core_register_export_type (struct pw_core * core, struct pw_export_type * type)
register a type that can be exported on a remote.
This is usually used by extension modules
References pw_log::pw_log_debug, pw_type_info(), and pw_export_type::type.
pw_remote_add_listener()
void pw_remote_add_listener (struct pw_remote * remote, struct spa_hook * listener, const struct pw_remote_events * events, void * data)
Add listener for events.
pw_remote_export()
struct pw_proxy* pw_remote_export (struct pw_remote * remote, uint32_t type, struct pw_properties * properties, void * object, size_t user_data_size)
run a local node in a remote graph
Parameters
remote the remote
type the type of object
properties extra properties
object object to export
user_data_size extra user data
References pw_export_type::func, pw_core_find_export_type(), pw_log::pw_log_error, and pw_export_type::type.
pw_remote_find_proxy()
struct pw_proxy* pw_remote_find_proxy (struct pw_remote * remote, uint32_t id)
Get the proxy with the given id.
References pw_map::pw_map_lookup().
pw_remote_get_client_proxy()
struct pw_client_proxy* pw_remote_get_client_proxy (struct pw_remote * remote)
Get the client proxy, can only be called when connected.
pw_remote_get_core()
struct pw_core* pw_remote_get_core (struct pw_remote * remote)
Get the core used to construct this remote.
pw_remote_get_core_proxy()
struct pw_core_proxy* pw_remote_get_core_proxy (struct pw_remote * remote)
Get the core proxy, can only be called when connected.
pw_remote_get_properties()
const struct pw_properties* pw_remote_get_properties (struct pw_remote * remote)
Get the remote properties.
Referenced by pw_stream_new().
pw_remote_get_state()
enum pw_remote_state pw_remote_get_state (struct pw_remote * remote, const char ** error)
Get the current state, error is set when state is PW_REMOTE_STATE_ERROR.
pw_remote_get_user_data()
void* pw_remote_get_user_data (struct pw_remote * remote)
Get the user_data.
The size was given in pw_remote_new
pw_remote_steal_fd()
int pw_remote_steal_fd (struct pw_remote * remote)
Steal the fd of the remote connection or < 0 on error.
The remote will be in the unconnected state after this call.
References pw_protocol_client_steal_fd.
pw_remote_update_properties()
int pw_remote_update_properties (struct pw_remote * remote, const struct spa_dict * dict)
Update properties.
References pw_properties::dict, pw_client_proxy_update_properties, pw_log::pw_log_debug, and pw_properties::pw_properties_update().