PipeWire: resource.h File Reference
resource.h File Reference
Data Structures
struct pw_resource_events
Resource events.
Macros
#define PW_VERSION_RESOURCE_EVENTS 0
#define pw_resource_notify(r, type, event, version, ...)
#define pw_resource_call(r, type, method, version, ...)
#define pw_resource_call_res(r, type, method, version, ...)
Functions
struct pw_resource * pw_resource_new (struct pw_client *client, uint32_t id, uint32_t permissions, uint32_t type, uint32_t version, size_t user_data_size)
Make a new resource for client.
void pw_resource_destroy (struct pw_resource *resource)
Destroy a resource.
struct pw_client * pw_resource_get_client (struct pw_resource *resource)
Get the client owning this resource.
uint32_t pw_resource_get_id (struct pw_resource *resource)
Get the unique id of this resource.
uint32_t pw_resource_get_permissions (struct pw_resource *resource)
Get the permissions of this resource.
uint32_t pw_resource_get_type (struct pw_resource *resource)
Get the type of this resource.
struct pw_protocol * pw_resource_get_protocol (struct pw_resource *resource)
Get the protocol used for this resource.
void * pw_resource_get_user_data (struct pw_resource *resource)
Get the user data for the resource, the size was given in pw_resource_new.
void pw_resource_add_listener (struct pw_resource *resource, struct spa_hook *listener, const struct pw_resource_events *events, void *data)
Add an event listener.
void pw_resource_add_object_listener (struct pw_resource *resource, struct spa_hook *listener, const void *funcs, void *data)
Set the resource implementation.
int pw_resource_ping (struct pw_resource *resource, int seq)
Generate an ping event for a resource.
void pw_resource_error (struct pw_resource *resource, int res, const char *error,...)
Generate an error for a resource.
struct spa_hook_list * pw_resource_get_object_listeners (struct pw_resource *resource)
Get the list of object listeners from a resource.
const struct pw_protocol_marshal * pw_resource_get_marshal (struct pw_resource *resource)
Get the marshal functions for the resource.
Macro Definition Documentation
pw_resource_call
#define pw_resource_call (r, type, method, version, ...)
Value:
spa_interface_call((struct spa_interface*)r,                    \
                        type, method, version, ##__VA_ARGS__)
pw_resource_call_res
#define pw_resource_call_res (r, type, method, version, ...)
Value:
({                                                                      \
        int _res = -ENOTSUP;                                            \
        spa_interface_call_res((struct spa_interface*)r,                \
                        type, _res, method, version, ##__VA_ARGS__);    \
        _res;                                                           \
})
pw_resource_notify
#define pw_resource_notify (r, type, event, version, ...)
Value:
spa_hook_list_call(pw_resource_get_object_listeners(r),         \
                        type, event, version, ## __VA_ARGS__)
PW_VERSION_RESOURCE_EVENTS
#define PW_VERSION_RESOURCE_EVENTS 0
Function Documentation
pw_resource_add_listener()
void pw_resource_add_listener (struct pw_resource * resource, struct spa_hook * listener, const struct pw_resource_events * events, void * data)
Add an event listener.
pw_resource_add_object_listener()
void pw_resource_add_object_listener (struct pw_resource * resource, struct spa_hook * listener, const void * funcs, void * data)
Set the resource implementation.
pw_resource_destroy()
void pw_resource_destroy (struct pw_resource * resource)
Destroy a resource.
References pw_log::pw_log_debug, and pw_map::pw_map_insert_at().
Referenced by pw_core::pw_core_destroy(), pw_global::pw_global_destroy(), and pw_global_update_permissions().
pw_resource_error()
void pw_resource_error (struct pw_resource * resource, int res, const char * error, ...)
Generate an error for a resource.
pw_resource_get_client()
struct pw_client* pw_resource_get_client (struct pw_resource * resource)
Get the client owning this resource.
pw_resource_get_id()
uint32_t pw_resource_get_id (struct pw_resource * resource)
Get the unique id of this resource.
pw_resource_get_marshal()
const struct pw_protocol_marshal* pw_resource_get_marshal (struct pw_resource * resource)
Get the marshal functions for the resource.
pw_resource_get_object_listeners()
struct spa_hook_list* pw_resource_get_object_listeners (struct pw_resource * resource)
Get the list of object listeners from a resource.
pw_resource_get_permissions()
uint32_t pw_resource_get_permissions (struct pw_resource * resource)
Get the permissions of this resource.
pw_resource_get_protocol()
struct pw_protocol* pw_resource_get_protocol (struct pw_resource * resource)
Get the protocol used for this resource.
pw_resource_get_type()
uint32_t pw_resource_get_type (struct pw_resource * resource)
Get the type of this resource.
pw_resource_get_user_data()
void* pw_resource_get_user_data (struct pw_resource * resource)
Get the user data for the resource, the size was given in pw_resource_new.
pw_resource_new()
struct pw_resource* pw_resource_new (struct pw_client * client, uint32_t id, uint32_t permissions, uint32_t type, uint32_t version, size_t user_data_size)
Make a new resource for client.
Parameters
client the client owning the resource
id the remote per client id
permissions permissions on this resource
type interface of the resource
version requested interface version
user_data_size extra user data size
References pw_log::pw_log_debug, pw_log::pw_log_error, pw_map::pw_map_insert_at(), pw_protocol_get_marshal(), pw_type_info(), and impl::this.
pw_resource_ping()
int pw_resource_ping (struct pw_resource * resource, int seq)
Generate an ping event for a resource.
This will generate a pong event with the same sequence number in the return value.
References pw_log::pw_log_debug.