PipeWire: stream.h File Reference
stream.h File Reference
Data Structures
struct pw_buffer
struct pw_stream_control
struct pw_stream_events
Events for a stream.
struct pw_time
A time structure.
Macros
#define PW_VERSION_STREAM_EVENTS 0
Enumerations
enum pw_stream_state {
PW_STREAM_STATE_ERROR = -1,
PW_STREAM_STATE_UNCONNECTED = 0,
PW_STREAM_STATE_CONNECTING = 1,
PW_STREAM_STATE_CONFIGURE = 2,
PW_STREAM_STATE_READY = 3,
PW_STREAM_STATE_PAUSED = 4,
PW_STREAM_STATE_STREAMING = 5
}
The state of a stream.
enum pw_stream_flags {
PW_STREAM_FLAG_NONE = 0,
PW_STREAM_FLAG_AUTOCONNECT = (1 << 0),
PW_STREAM_FLAG_INACTIVE = (1 << 1),
PW_STREAM_FLAG_MAP_BUFFERS = (1 << 2),
PW_STREAM_FLAG_DRIVER = (1 << 3),
PW_STREAM_FLAG_RT_PROCESS = (1 << 4),
PW_STREAM_FLAG_NO_CONVERT = (1 << 5),
PW_STREAM_FLAG_EXCLUSIVE = (1 << 6),
PW_STREAM_FLAG_DONT_RECONNECT = (1 << 7),
PW_STREAM_FLAG_ALLOC_BUFFERS = (1 << 8)
}
Extra flags that can be used in pw_stream_connect()
Functions
struct pw_stream * pw_stream_new_simple (struct pw_loop *loop, const char *name, struct pw_properties *props, const struct pw_stream_events *events, void *data)
void pw_stream_add_listener (struct pw_stream *stream, struct spa_hook *listener, const struct pw_stream_events *events, void *data)
enum pw_stream_state pw_stream_get_state (struct pw_stream *stream, const char **error)
const char * pw_stream_get_name (struct pw_stream *stream)
struct pw_remote * pw_stream_get_remote (struct pw_stream *stream)
const struct pw_properties * pw_stream_get_properties (struct pw_stream *stream)
int pw_stream_update_properties (struct pw_stream *stream, const struct spa_dict *dict)
int pw_stream_set_control (struct pw_stream *stream, uint32_t id, float value,...)
Set control values.
const struct pw_stream_control * pw_stream_get_control (struct pw_stream *stream, uint32_t id)
Get control information.
struct pw_buffer * pw_stream_dequeue_buffer (struct pw_stream *stream)
Get a buffer that can be filled for playback streams or consumed for capture streams.
int pw_stream_queue_buffer (struct pw_stream *stream, struct pw_buffer *buffer)
Submit a buffer for playback or recycle a buffer for capture.
int pw_stream_flush (struct pw_stream *stream, bool drain)
Flush a stream.
Macro Definition Documentation
PW_VERSION_STREAM_EVENTS
#define PW_VERSION_STREAM_EVENTS 0
Enumeration Type Documentation
pw_stream_flags
enum pw_stream_flags
Extra flags that can be used in pw_stream_connect()
Enumerator
PW_STREAM_FLAG_NONE
no flags
PW_STREAM_FLAG_AUTOCONNECT
try to automatically connect this stream
PW_STREAM_FLAG_INACTIVE
start the stream inactive, pw_stream_set_active() needs to be called explicitly
PW_STREAM_FLAG_MAP_BUFFERS
mmap the buffers
PW_STREAM_FLAG_DRIVER
be a driver
PW_STREAM_FLAG_RT_PROCESS
call process from the realtime thread
PW_STREAM_FLAG_NO_CONVERT
don't convert format
PW_STREAM_FLAG_EXCLUSIVE
require exclusive access to the device
PW_STREAM_FLAG_DONT_RECONNECT
don't try to reconnect this stream when the sink/source is removed
PW_STREAM_FLAG_ALLOC_BUFFERS
the application will allocate buffer memory.
In the add_buffer event, the data of the buffer should be set
pw_stream_state
enum pw_stream_state
The state of a stream.
Enumerator
PW_STREAM_STATE_ERROR
the strean is in error
PW_STREAM_STATE_UNCONNECTED
unconnected
PW_STREAM_STATE_CONNECTING
connection is in progress
PW_STREAM_STATE_CONFIGURE
stream is being configured
PW_STREAM_STATE_READY
stream is ready
PW_STREAM_STATE_PAUSED
paused, fully configured but not processing data yet
PW_STREAM_STATE_STREAMING
streaming
Function Documentation
pw_stream_add_listener()
void pw_stream_add_listener (struct pw_stream * stream, struct spa_hook * listener, const struct pw_stream_events * events, void * data)
Referenced by pw_stream_new_simple().
pw_stream_dequeue_buffer()
struct pw_buffer* pw_stream_dequeue_buffer (struct pw_stream * stream)
Get a buffer that can be filled for playback streams or consumed for capture streams.
pw_stream_flush()
int pw_stream_flush (struct pw_stream * stream, bool drain)
Flush a stream.
When drain is true, the drained callback will be called when all data is played or recorded
References pw_loop_invoke.
pw_stream_get_control()
const struct pw_stream_control* pw_stream_get_control (struct pw_stream * stream, uint32_t id)
Get control information.
pw_stream_get_name()
const char* pw_stream_get_name (struct pw_stream * stream)
pw_stream_get_properties()
const struct pw_properties* pw_stream_get_properties (struct pw_stream * stream)
pw_stream_get_remote()
struct pw_remote* pw_stream_get_remote (struct pw_stream * stream)
pw_stream_get_state()
enum pw_stream_state pw_stream_get_state (struct pw_stream * stream, const char ** error)
pw_stream_new_simple()
struct pw_stream* pw_stream_new_simple (struct pw_loop * loop, const char * name, struct pw_properties * props, const struct pw_stream_events * events, void * data)
Parameters
loop a pw_loop to use
name a stream name
props stream properties, ownership is taken
events stream events
data data passed to events
References pw_core::pw_core_destroy(), pw_core::pw_core_new(), pw_remote::pw_remote_new(), pw_stream_add_listener(), and pw_stream::pw_stream_new().
pw_stream_queue_buffer()
int pw_stream_queue_buffer (struct pw_stream * stream, struct pw_buffer * buffer)
Submit a buffer for playback or recycle a buffer for capture.
References buffer::id, NAME, and pw_log::pw_log_trace.
pw_stream_set_control()
int pw_stream_set_control (struct pw_stream * stream, uint32_t id, float value, ...)
Set control values.
References NAME, and pw_log::pw_log_debug.
pw_stream_update_properties()
int pw_stream_update_properties (struct pw_stream * stream, const struct spa_dict * dict)
References pw_node_update_properties(), and pw_properties::pw_properties_update().