PipeWire: pw_properties Class Reference
pw_properties Class Reference
A collection of key/value pairs.
Public Member Functions
SPA_EXPORT struct pw_properties * pw_properties_new (const char *key,...)
Make a new properties object.
SPA_EXPORT struct pw_properties * pw_properties_new_dict (const struct spa_dict *dict)
Make a new properties object from the given dictionary.
SPA_EXPORT struct pw_properties * pw_properties_new_string (const char *str)
Make a new properties object from the given str.
SPA_EXPORT struct pw_properties * pw_properties_copy (const struct pw_properties *properties)
Copy a properties object.
SPA_EXPORT void pw_properties_clear (struct pw_properties *properties)
Clear a properties object.
SPA_EXPORT int pw_properties_update (struct pw_properties *props, const struct spa_dict *dict)
Update properties.
SPA_EXPORT void pw_properties_free (struct pw_properties *properties)
Free a properties object.
SPA_EXPORT int pw_properties_set (struct pw_properties *properties, const char *key, const char *value)
Set a property value.
SPA_EXPORT int pw_properties_setf (struct pw_properties *properties, const char *key, const char *format,...)
Set a property value by format.
SPA_EXPORT const char * pw_properties_get (const struct pw_properties *properties, const char *key)
Get a property.
SPA_EXPORT const char * pw_properties_iterate (const struct pw_properties *properties, void **state)
Iterate property values.
Data Fields
struct spa_dict dict
dictionary of key/values
uint32_t flags
extra flags
Detailed Description
A collection of key/value pairs.
Properties are used to pass around arbitrary key/value pairs. Both keys and values are strings which keeps things simple. Encoding of arbitrary values should be done by using a string serialization such as base64 for binary blobs.
Member Function Documentation
pw_properties_clear()
SPA_EXPORT void pw_properties_clear (struct pw_properties * properties)
Clear a properties object.
Parameters
properties properties to clear
References pw_array_for_each.
Referenced by pw_properties_free().
pw_properties_copy()
SPA_EXPORT struct pw_properties * pw_properties_copy (const struct pw_properties * properties)
Copy a properties object.
Parameters
properties properties to copy
Returns
a new properties object
References dict, and pw_properties_new_dict().
Referenced by pw_core::pw_core_new().
pw_properties_free()
SPA_EXPORT void pw_properties_free (struct pw_properties * properties)
Free a properties object.
Parameters
properties the properties to free
References pw_properties_clear().
Referenced by pw_core::pw_core_destroy(), pw_device_destroy(), pw_device_new(), pw_factory_destroy(), pw_global::pw_global_new(), pw_loop::pw_loop_destroy(), pw_loop::pw_loop_new(), pw_mempool_destroy(), pw_module::pw_module_destroy(), pw_remote_destroy(), and pw_remote_new().
pw_properties_get()
SPA_EXPORT const char * pw_properties_get (const struct pw_properties * properties, const char * key)
Get a property.
Parameters
properties a pw_properties
key a key
Returns
the property for key or NULL when the key was not found
Get the property in properties with key.
Referenced by pw_core::pw_core_new(), pw_device_register(), pw_pipewire::pw_fill_remote_properties(), pw_loop::pw_loop_new(), pw_node_register(), pw_remote_new(), and pw_stream_new().
pw_properties_iterate()
SPA_EXPORT const char * pw_properties_iterate (const struct pw_properties * properties, void ** state)
Iterate property values.
Parameters
properties a pw_properties
state state
Returns
The next key or NULL when there are no more keys to iterate.
Iterate over properties, returning each key in turn. state should point to a pointer holding NULL to get the first element and will be updated after each iteration. When NULL is returned, all elements have been iterated.
References pw_array::pw_array_check_index, and pw_array::pw_array_get_unchecked.
pw_properties_new()
SPA_EXPORT struct pw_properties * pw_properties_new (const char * key, ...)
Make a new properties object.
Parameters
key a first key
... value and more keys NULL terminated
Returns
a newly allocated properties object
Referenced by pw_client::pw_client_new(), pw_core::pw_core_new(), pw_device_new(), pw_device_register(), pw_factory_register(), pw_link_register(), pw_node_new(), pw_node_register(), pw_port_new(), pw_remote_new(), and pw_stream_new().
pw_properties_new_dict()
SPA_EXPORT struct pw_properties * pw_properties_new_dict (const struct spa_dict * dict)
Make a new properties object from the given dictionary.
Parameters
dict a dictionary. keys and values are copied
Returns
a new properties object
Referenced by pw_port_new(), and pw_properties_copy().
pw_properties_new_string()
SPA_EXPORT struct pw_properties * pw_properties_new_string (const char * str)
Make a new properties object from the given str.
str should be a whitespace separated list of key=value strings.
Parameters
args a property description
Returns
a new properties object
pw_properties_set()
SPA_EXPORT int pw_properties_set (struct pw_properties * properties, const char * key, const char * value)
Set a property value.
Parameters
properties the properties to change
key a key
value a value or NULL to remove the key
Returns
1 if the properties were changed. 0 if nothing was changed because the property already existed with the same value or because the key to remove did not exist.
Set the property in properties with key to value. Any previous value of key will be overwritten. When value is NULL, the key will be removed.
Referenced by pw_core::pw_core_new(), pw_device_register(), pw_factory_register(), pw_pipewire::pw_fill_remote_properties(), pw_node_register(), pw_port_new(), pw_properties_update(), and pw_stream_new().
pw_properties_setf()
SPA_EXPORT int pw_properties_setf (struct pw_properties * properties, const char * key, const char * format, ...)
Set a property value by format.
Parameters
properties a pw_properties
key a key
format a value
... extra arguments
Set the property in properties with key to the value in printf style format Any previous value of key will be overwritten.
References pw_properties_setva().
Referenced by pw_core::pw_core_new(), pw_factory_register(), pw_pipewire::pw_fill_remote_properties(), and pw_link_register().
pw_properties_update()
SPA_EXPORT int pw_properties_update (struct pw_properties * props, const struct spa_dict * dict)
Update properties.
Parameters
props properties to update
dict new properties
Returns
the number of changed properties
The properties in props are updated with dict. Keys in dict with NULL values are removed from props.
References pw_properties_set().
Referenced by pw_client::pw_client_update_properties(), pw_core::pw_core_update_properties(), pw_module_update_properties(), pw_remote_update_properties(), and pw_stream_update_properties().
Field Documentation
dict
struct spa_dict pw_properties::dict
dictionary of key/values
Referenced by pw_core::pw_core_new(), pw_device_new(), pw_factory_new(), pw_loop::pw_loop_new(), pw_port_new(), pw_properties_copy(), and pw_remote_update_properties().
flags
uint32_t pw_properties::flags
extra flags
The documentation for this class was generated from the following files:
properties.h
properties.c