PipeWire: pw_loop Class Reference
pw_loop Class Reference
PipeWire loop object provides an implementation of the spa loop interfaces.
Public Member Functions
SPA_EXPORT struct pw_loop * pw_loop_new (struct pw_properties *properties)
Create a new loop.
SPA_EXPORT void pw_loop_destroy (struct pw_loop *loop)
Destroy a loop.
Data Fields
struct spa_system * system
system utils
struct spa_loop * loop
wrapped loop
struct spa_loop_control * control
loop control
struct spa_loop_utils * utils
loop utils
Detailed Description
PipeWire loop object provides an implementation of the spa loop interfaces.
It can be used to implement various event loops.
Member Function Documentation
pw_loop_destroy()
SPA_EXPORT void pw_loop_destroy (struct pw_loop * loop)
Destroy a loop.
Parameters
loop a loop to destroy
References pw_properties::pw_properties_free(), and pw_unload_spa_handle().
Referenced by pw_data_loop::pw_data_loop_destroy(), and pw_main_loop::pw_main_loop_destroy().
pw_loop_new()
SPA_EXPORT struct pw_loop * pw_loop_new (struct pw_properties * properties)
Create a new loop.
Returns
a newly allocated loop
References pw_properties::dict, pw_get_support(), PW_KEY_LIBRARY_NAME_LOOP, PW_KEY_LIBRARY_NAME_SYSTEM, pw_load_spa_handle(), pw_log::pw_log_error, pw_properties::pw_properties_free(), pw_properties::pw_properties_get(), pw_unload_spa_handle(), and impl::this.
Referenced by pw_data_loop::pw_data_loop_new(), and pw_main_loop::pw_main_loop_new().
Field Documentation
control
struct spa_loop_control* pw_loop::control
loop control
loop
struct spa_loop* pw_loop::loop
wrapped loop
Referenced by pw_core::pw_core_new(), pw_data_loop_get_loop(), pw_data_loop::pw_data_loop_in_thread(), pw_data_loop::pw_data_loop_start(), pw_data_loop::pw_data_loop_stop(), pw_main_loop_get_loop(), pw_main_loop::pw_main_loop_quit(), pw_main_loop::pw_main_loop_run(), and pw_thread_loop_get_loop().
system
struct spa_system* pw_loop::system
system utils
Referenced by pw_core::pw_core_new().
utils
struct spa_loop_utils* pw_loop::utils
loop utils
Referenced by pw_core::pw_core_new().
The documentation for this class was generated from the following files:
loop.h
loop.c