PipeWire: type.h File Reference
type.h File Reference
Macros
#define PW_TYPE_INFO_BASE "PipeWire:"
#define PW_TYPE_INFO_Object PW_TYPE_INFO_BASE "Object"
#define PW_TYPE_INFO_OBJECT_BASE PW_TYPE_INFO_Object ":"
#define PW_TYPE_INFO_Interface PW_TYPE_INFO_BASE "Interface"
#define PW_TYPE_INFO_INTERFACE_BASE PW_TYPE_INFO_Interface ":"
Enumerations
enum {
PW_TYPE_FIRST = SPA_TYPE_VENDOR_PipeWire,
PW_TYPE_INTERFACE_START = PW_TYPE_FIRST + SPA_TYPE_INTERFACE_START,
PW_TYPE_INTERFACE_Core,
PW_TYPE_INTERFACE_Registry,
PW_TYPE_INTERFACE_Node,
PW_TYPE_INTERFACE_Port,
PW_TYPE_INTERFACE_Factory,
PW_TYPE_INTERFACE_Link,
PW_TYPE_INTERFACE_Client,
PW_TYPE_INTERFACE_Module,
PW_TYPE_INTERFACE_Device,
PW_TYPE_INTERFACE_EXTENSIONS = PW_TYPE_INTERFACE_START + 0x1000,
PW_TYPE_INTERFACE_ClientNode
}
Functions
const struct spa_type_info * pw_type_info (void)
Macro Definition Documentation
PW_TYPE_INFO_BASE
#define PW_TYPE_INFO_BASE "PipeWire:"
PW_TYPE_INFO_Interface
#define PW_TYPE_INFO_Interface PW_TYPE_INFO_BASE "Interface"
PW_TYPE_INFO_INTERFACE_BASE
#define PW_TYPE_INFO_INTERFACE_BASE PW_TYPE_INFO_Interface ":"
PW_TYPE_INFO_Object
#define PW_TYPE_INFO_Object PW_TYPE_INFO_BASE "Object"
PW_TYPE_INFO_OBJECT_BASE
#define PW_TYPE_INFO_OBJECT_BASE PW_TYPE_INFO_Object ":"
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PW_TYPE_FIRST
PW_TYPE_INTERFACE_START
PW_TYPE_INTERFACE_Core
PW_TYPE_INTERFACE_Registry
PW_TYPE_INTERFACE_Node
PW_TYPE_INTERFACE_Port
PW_TYPE_INTERFACE_Factory
PW_TYPE_INTERFACE_Link
PW_TYPE_INTERFACE_Client
PW_TYPE_INTERFACE_Module
PW_TYPE_INTERFACE_Device
PW_TYPE_INTERFACE_EXTENSIONS
PW_TYPE_INTERFACE_ClientNode
Function Documentation
pw_type_info()
const struct spa_type_info* pw_type_info (void)
Referenced by pw_core_register_export_type(), pw_factory_register(), pw_global::pw_global_new(), pw_protocol_add_marshal(), pw_proxy::pw_proxy_new(), and pw_resource_new().